"""
Analytics module for codebase statistics and quantitative queries.

This module provides access to codebase statistics and metrics for
answering quantitative questions about the egeria-python repository.
"""

import json
from pathlib import Path
from typing import Dict, Any, Optional, List
from loguru import logger

from advisor.config import settings


class AnalyticsManager:
    """Manages codebase analytics and statistics."""
    
    def __init__(self, cache_dir: Optional[Path] = None):
        """
        Initialize analytics manager.
        
        Args:
            cache_dir: Directory containing cached statistics
        """
        self.cache_dir = cache_dir or Path(settings.advisor_cache_dir)
        self.stats: Optional[Dict[str, Any]] = None
        self.directory_stats: Optional[Dict[str, Any]] = None
        self._load_statistics()
        self._load_directory_statistics()
    
    def _load_statistics(self):
        """Load statistics from cache."""
        # Use enhanced_metrics.json which is generated by the current pipeline
        enhanced_file = self.cache_dir / "enhanced_metrics.json"
        
        if not enhanced_file.exists():
            # Fallback to older pipeline summary if it exists
            summary_file = self.cache_dir / "pipeline_summary.json"
            if not summary_file.exists():
                logger.warning(f"Statistics file not found: {enhanced_file}")
                self.stats = {}
                return
            enhanced_file = summary_file
        
        try:
            with open(enhanced_file, 'r') as f:
                data = json.load(f)
                
                # If it's the enhanced format, we need to map it to the expected schema
                if "files_analyzed" in data:
                    self.stats = {
                        "code": {
                            "total": data.get("total_sloc", 0),
                            "by_type": {
                                "class": data.get("total_classes", 0),
                                "function": data.get("total_functions", 0),
                                "method": data.get("total_methods", 0),
                            },
                            "avg_complexity": data.get("avg_complexity", 0.0),
                            "total_complexity": data.get("total_complexity", 0),
                        },
                        "metadata": {
                            "total_files": data.get("files_analyzed", 0),
                            "by_type": {
                                "python": data.get("total_python_files", 0), 
                                "java": data.get("total_java_files", 0),
                                "packages": data.get("total_packages", 0)
                            },
                            "total_lines": data.get("total_loc", 0),
                            "total_size_bytes": sum(f.get("size", 0) for f in data.get("file_metrics", [])),
                        },
                        "cli_commands": data.get("cli_commands", []),
                        "relationships": data.get("relationships", {})
                    }
                    # Try to get more granular stats if available in by_folder
                    if "by_folder" in data:
                        self.directory_stats = data["by_folder"]
                else:
                    self.stats = data.get("statistics", {})
                    
            logger.info(f"Loaded statistics from {enhanced_file}")
        except Exception as e:
            logger.error(f"Failed to load statistics: {e}")
            self.stats = {}
    
    def _load_directory_statistics(self):
        """Load per-directory statistics from cache."""
        dir_stats_file = self.cache_dir / "directory_stats.json"
        
        if not dir_stats_file.exists():
            logger.warning(f"Directory statistics file not found: {dir_stats_file}")
            logger.info("Run scripts/generate_directory_stats.py to enable scoped queries")
            self.directory_stats = {}
            return
        
        try:
            with open(dir_stats_file, 'r') as f:
                self.directory_stats = json.load(f)
            logger.info(f"Loaded directory statistics from {dir_stats_file}")
            logger.info(f"Directories available: {', '.join([d for d in self.directory_stats.keys() if d != '_total'])}")
        except Exception as e:
            logger.error(f"Failed to load directory statistics: {e}")
            self.directory_stats = {}
    
    def get_total_classes(self, path_filter: Optional[str] = None) -> int:
        """
        Get total number of classes, optionally filtered by path.
        
        Args:
            path_filter: Optional directory path to filter by (e.g., "pyegeria")
            
        Returns:
            Count of classes
        """
        if path_filter and self.directory_stats:
            # Normalize path filter
            path_filter = path_filter.lower().strip('/')
            dir_data = self.directory_stats.get(path_filter, {})
            return dir_data.get('classes', 0)
        return self.stats.get("code", {}).get("by_type", {}).get("class", 0)
    
    def get_total_functions(self, path_filter: Optional[str] = None) -> int:
        """
        Get total number of functions, optionally filtered by path.
        
        Args:
            path_filter: Optional directory path to filter by
            
        Returns:
            Count of functions
        """
        if path_filter and self.directory_stats:
            path_filter = path_filter.lower().strip('/')
            dir_data = self.directory_stats.get(path_filter, {})
            return dir_data.get('functions', 0)
        return self.stats.get("code", {}).get("by_type", {}).get("function", 0)
    
    def get_total_methods(self, path_filter: Optional[str] = None) -> int:
        """
        Get total number of methods, optionally filtered by path.
        
        Args:
            path_filter: Optional directory path to filter by
            
        Returns:
            Count of methods
        """
        if path_filter and self.directory_stats:
            path_filter = path_filter.lower().strip('/')
            dir_data = self.directory_stats.get(path_filter, {})
            return dir_data.get('methods', 0)
        return self.stats.get("code", {}).get("by_type", {}).get("method", 0)
    
    def get_total_code_elements(self) -> int:
        """Get total number of code elements (classes + functions + methods)."""
        return self.stats.get("code", {}).get("total", 0)
    
    def get_total_files(self) -> int:
        """Get total number of files."""
        return self.stats.get("metadata", {}).get("total_files", 0)
    
    def get_total_python_files(self) -> int:
        """Get total number of Python files."""
        return self.stats.get("metadata", {}).get("by_type", {}).get("python", 0)
    
    def get_total_lines_of_code(self) -> int:
        """Get total lines of code."""
        return self.stats.get("metadata", {}).get("total_lines", 0)
    
    def get_total_size_bytes(self) -> int:
        """Get total codebase size in bytes."""
        return self.stats.get("metadata", {}).get("total_size_bytes", 0)
    
    def get_files_by_category(self) -> Dict[str, int]:
        """Get file counts by category."""
        return self.stats.get("metadata", {}).get("by_category", {})
    
    def get_public_elements_count(self) -> int:
        """Get count of public code elements."""
        return self.stats.get("code", {}).get("public_elements", 0)
    
    def get_elements_with_docstrings(self) -> int:
        """Get count of elements with docstrings."""
        return self.stats.get("code", {}).get("with_docstrings", 0)
    
    def get_average_complexity(self) -> float:
        """Get average cyclomatic complexity."""
        return self.stats.get("code", {}).get("avg_complexity", 0.0)
    
    def get_total_documentation_sections(self) -> int:
        """Get total documentation sections."""
        return self.stats.get("documentation", {}).get("total", 0)
    
    def get_total_examples(self) -> int:
        """Get total number of examples."""
        return self.stats.get("examples", {}).get("total", 0)
    
    def get_examples_by_type(self) -> Dict[str, int]:
        """Get example counts by type."""
        return self.stats.get("examples", {}).get("by_type", {})
    
    def get_summary(self) -> Dict[str, Any]:
        """Get a comprehensive summary of statistics."""
        return {
            "code": {
                "total_elements": self.get_total_code_elements(),
                "classes": self.get_total_classes(),
                "functions": self.get_total_functions(),
                "methods": self.get_total_methods(),
                "public_elements": self.get_public_elements_count(),
                "with_docstrings": self.get_elements_with_docstrings(),
                "avg_complexity": self.get_average_complexity(),
            },
            "files": {
                "total": self.get_total_files(),
                "python": self.get_total_python_files(),
                "by_category": self.get_files_by_category(),
            },
            "size": {
                "total_bytes": self.get_total_size_bytes(),
                "total_lines": self.get_total_lines_of_code(),
            },
            "documentation": {
                "sections": self.get_total_documentation_sections(),
            },
            "examples": {
                "total": self.get_total_examples(),
                "by_type": self.get_examples_by_type(),
            }
        }
    
    # ── symbol-store helpers ────────────────────────────────────────────────

    def _symbol_store(self):
        """AST-ownership-transfer plan Phase 7 — reads Resource Explorer's
        resource_explorer.project_code_symbols (cross-schema, same Postgres
        instance) via ReCodeSymbolReader instead of EA's own CodeSymbolStore.
        ReCodeSymbolReader mirrors CodeSymbolStore's exact method names/
        return shapes (project_slug aliased as `collection` in every row),
        so nothing below this line needed to change."""
        try:
            from advisor.re_code_symbol_reader import get_re_code_symbol_reader
            return get_re_code_symbol_reader()
        except Exception:
            return None

    @staticmethod
    def _collection_for_filter(path_filter: Optional[str]) -> Optional[str]:
        """Map a user-supplied path filter to a canonical collection name."""
        if not path_filter:
            return None
        pf = path_filter.lower().replace("-", "_").replace(" ", "_")
        aliases = {
            "pyegeria": "pyegeria",
            "pyegeria_cli": "pyegeria_cli",
            "cli": "pyegeria_cli",
            "pyegeria_dre": "pyegeria_drE",
            "pyegeria_dre": "pyegeria_dre",
            "dre": "pyegeria_drE",
            "dr_egeria": "pyegeria_drE",
            "egeria_java": "egeria_java",
            "java": "egeria_java",
        }
        return aliases.get(pf, pf)

    def _format_class_list(self, rows: list, collection_label: str) -> str:
        if not rows:
            return f"No classes found in {collection_label}."
        lines = [f"**{len(rows)} classes** in {collection_label}:\n"]
        for r in rows:
            loc = r.get("loc", 0)
            doc = (r.get("docstring") or "").split("\n")[0][:80]
            suffix = f" — {doc}" if doc else ""
            lines.append(f"- `{r['name']}` ({loc} lines){suffix}")
        return "\n".join(lines)

    def _format_method_list(self, rows: list, class_name: str) -> str:
        if not rows:
            return f"No public methods found for `{class_name}`."
        lines = [f"**{len(rows)} public methods** on `{class_name}`:\n"]
        for r in rows:
            sig = r.get("signature") or r["name"]
            doc = (r.get("docstring") or "").split("\n")[0][:80]
            async_tag = " *(async)*" if r.get("is_async") else ""
            lines.append(f"- `{sig}`{async_tag}" + (f" — {doc}" if doc else ""))
        return "\n".join(lines)

    def _format_symbol_search(self, rows: list, pattern: str) -> str:
        if not rows:
            return f"No symbols matching `{pattern}` found."
        lines = [f"**{len(rows)} symbols** matching `{pattern}`:\n"]
        for r in rows:
            parent = f" in `{r['parent_class']}`" if r.get("parent_class") else ""
            lines.append(f"- `{r['kind']}` **{r['name']}**{parent} ({r['collection']})")
        return "\n".join(lines)

    def _collection_summary_text(self, ss, collection: Optional[str]) -> str:
        summary = ss.collection_summary(collection)
        if not summary:
            return "No symbol data available yet — re-run ingestion to populate the symbol table."
        lines = ["**Collection symbol summary:**\n"]
        for col, data in sorted(summary.items()):
            lines.append(
                f"**{col}**: {data.get('classes', 0)} classes · "
                f"{data.get('methods', 0)} methods · "
                f"{data.get('functions', 0)} functions · "
                f"~{data.get('loc', 0):,} LOC"
            )
        return "\n".join(lines)

    def answer_quantitative_query(self, query: str, path_filter: Optional[str] = None) -> str:
        """
        Answer a quantitative query about the codebase.

        Args:
            query: User's quantitative question
            path_filter: Optional directory path to filter by (e.g., "pyegeria")

        Returns:
            Formatted answer with statistics
        """
        query_lower = query.lower()
        ss = self._symbol_store()
        collection = self._collection_for_filter(path_filter)

        # Build scope description
        if collection:
            scope = f"the **{collection}** collection"
        elif path_filter:
            scope = f"the **{path_filter}** directory"
        else:
            scope = "the egeria-python codebase"

        # ── Live symbol-store queries (populated at ingest time) ──────────

        if ss:
            import re as _re

            # "largest/biggest class" — check BEFORE generic "classes in" list
            if any(p in query_lower for p in ("largest class", "biggest class",
                                               "most methods", "class with most")):
                rows = ss.largest_classes(collection, limit=10)
                if not rows:
                    return "No class data available yet."
                lines = [f"**Top {len(rows)} largest classes** in {scope}:\n"]
                for r in rows:
                    lines.append(
                        f"- **{r['name']}** — {r['method_count']} methods, "
                        f"{r.get('loc', 0)} lines ({r['collection']})"
                    )
                return "\n".join(lines)

            # "what classes are in pyegeria?" / "list classes in pyegeria_cli"
            if any(p in query_lower for p in ("what class", "list class", "show class",
                                               "which class", "classes in", "classes does")):
                rows = ss.list_classes(collection)
                return self._format_class_list(rows, scope)

            # "most complex methods" / "highest complexity" — check BEFORE class-method
            # regex so "most complex methods in pyegeria" doesn't misparse "pyegeria" as a class
            if any(p in query_lower for p in ("most complex", "highest complex",
                                               "complex method", "complex function")):
                rows = ss.most_complex(collection, limit=10)
                if not rows:
                    return "No complexity data available yet."
                lines = [f"**Top {len(rows)} most complex functions/methods** in {scope}:\n"]
                for r in rows:
                    parent = f"`{r['parent_class']}.`" if r.get("parent_class") else ""
                    lines.append(
                        f"- {parent}**{r['name']}** — complexity {r['complexity']}, "
                        f"{r.get('loc', 0)} lines ({r['collection']})"
                    )
                return "\n".join(lines)

            # "what methods does GlossaryManager have?" — require CamelCase to avoid
            # matching collection names like "pyegeria" as class names
            _class_method_re = _re.compile(
                r'(?:methods?\s+(?:does|on|of|for|in)\s+|methods?\s+available\s+(?:on|in)\s+'
                r'|what\s+(?:methods?|api)\s+does\s+|api\s+for\s+)([A-Z][A-Za-z0-9]+)',
            )
            m = _class_method_re.search(query)
            if m:
                class_name = m.group(1)
                rows = ss.methods_for_class(class_name, collection)
                return self._format_method_list(rows, class_name)

            # "find method X" / "search for symbol X"
            _search_re = _re.compile(
                r'(?:find|search\s+for|locate|where\s+is)\s+(?:method|function|class|symbol)?\s*["\']?(\w+)["\']?',
                _re.IGNORECASE,
            )
            ms = _search_re.search(query)
            if ms:
                pattern = ms.group(1)
                rows = ss.search_symbols(pattern, collection)
                return self._format_symbol_search(rows, pattern)

            # "collection summary" / "symbol summary" / "code summary"
            if any(p in query_lower for p in ("collection summar", "symbol summar",
                                               "code summar", "ingestion summar")):
                return self._collection_summary_text(ss, collection)

            # Enrich count queries with live data from symbol store
            if "how many class" in query_lower:
                count = ss.count_by_kind("class", collection)
                return f"There are **{count:,} classes** in {scope}."
            if "how many method" in query_lower:
                count = ss.count_by_kind("method", collection)
                return f"There are **{count:,} methods** in {scope}."
            if "how many function" in query_lower:
                count = ss.count_by_kind("function", collection)
                return f"There are **{count:,} functions** in {scope}."

        # ── Fall back to stale JSON cache for non-structural queries ──────

        # Detect what the user is asking about
        if "how many class" in query_lower:
            count = self.get_total_classes(path_filter)
            return f"There are **{count:,} classes** in {scope}."
        
        elif "cli command" in query_lower or "how many command" in query_lower:
            commands = self.stats.get("cli_commands", [])
            if not commands:
                return "I couldn't find any CLI command definitions in the current analysis."
            
            if "list" in query_lower or "what" in query_lower:
                sample = ", ".join([f"`{c['name']}`" for c in commands[:10]])
                return f"There are **{len(commands)} hey_egeria CLI commands** defined. Some examples include: {sample}."
            return f"There are **{len(commands)} hey_egeria CLI commands** available."
            
        elif "relationship" in query_lower or "depend" in query_lower or "structure" in query_lower:
            rels = self.stats.get("relationships", {})
            if not rels:
                return "I don't have enough information about codebase relationships yet."
            
            if "summary" in query_lower or "show" in query_lower or "how" in query_lower:
                summary = []
                for pkg, deps in sorted(rels.items())[:5]: # Top 5
                    summary.append(f"- **{pkg}** depends on: {', '.join(deps)}")
                return f"Here is a summary of internal module relationships:\n" + "\n".join(summary)
            
            return f"I have mapped relationships for **{len(rels)} modules** in the codebase."
        
        elif "how many function" in query_lower:
            count = self.get_total_functions(path_filter)
            return f"There are **{count:,} functions** in {scope}."
        
        elif "how many method" in query_lower:
            count = self.get_total_methods(path_filter)
            return f"There are **{count:,} methods** in {scope}."
        
        elif "how many file" in query_lower or "total file" in query_lower:
            total = self.get_total_files()
            python = self.get_total_python_files()
            return f"There are **{total:,} total files** in the codebase, including **{python:,} Python files**."
        
        elif "lines of code" in query_lower or "loc" in query_lower:
            lines = self.get_total_lines_of_code()
            return f"The codebase contains **{lines:,} lines of code**."
        
        elif "how many module" in query_lower or "python file" in query_lower:
            modules = self.stats.get("metadata", {}).get("by_type", {}).get("python", 0)
            packages = self.stats.get("metadata", {}).get("by_type", {}).get("packages", 0)
            if "package" in query_lower:
                return f"There are **{packages:,} Python packages** (directories with `__init__.py`) in the codebase."
            return f"There are **{modules:,} Python modules** and **{packages:,} packages** in the codebase."
        
        elif "size" in query_lower and ("codebase" in query_lower or "repository" in query_lower):
            size_bytes = self.get_total_size_bytes()
            size_mb = size_bytes / (1024 * 1024)
            return f"The codebase is **{size_mb:.1f} MB** ({size_bytes:,} bytes)."
        
        elif "docstring" in query_lower:
            count = self.get_elements_with_docstrings()
            total = self.get_total_code_elements()
            percentage = (count / total * 100) if total > 0 else 0
            return f"**{count:,} code elements** ({percentage:.1f}%) have docstrings."
        
        elif "public" in query_lower:
            count = self.get_public_elements_count()
            total = self.get_total_code_elements()
            percentage = (count / total * 100) if total > 0 else 0
            return f"**{count:,} code elements** ({percentage:.1f}%) are public."
        
        elif "complexity" in query_lower:
            avg = self.get_average_complexity()
            return f"The average cyclomatic complexity is **{avg:.2f}**."
        
        elif "example" in query_lower:
            count = self.get_total_examples()
            by_type = self.get_examples_by_type()
            details = ", ".join([f"{count} {type_}" for type_, count in by_type.items()])
            return f"There are **{count:,} examples** in the codebase ({details})."
        
        elif "documentation" in query_lower or "doc section" in query_lower:
            count = self.get_total_documentation_sections()
            return f"There are **{count:,} documentation sections** in the codebase."
        
        elif "category" in query_lower or "breakdown" in query_lower:
            by_category = self.get_files_by_category()
            lines = ["**Files by category:**"]
            for category, count in sorted(by_category.items(), key=lambda x: x[1], reverse=True):
                lines.append(f"- {category}: {count:,} files")
            return "\n".join(lines)
        
        elif "summary" in query_lower or "overview" in query_lower or "statistics" in query_lower:
            summary = self.get_summary()
            return self._format_summary(summary)
        
        else:
            # Default: provide a general summary
            return self._format_summary(self.get_summary())
    
    def _format_summary(self, summary: Dict[str, Any]) -> str:
        """Format a summary dictionary into a readable string."""
        lines = ["**Codebase Statistics:**\n"]
        
        # Code statistics
        code = summary["code"]
        lines.append(f"**Code Elements:** {code['total_elements']:,}")
        lines.append(f"  - Classes: {code['classes']:,}")
        lines.append(f"  - Functions: {code['functions']:,}")
        lines.append(f"  - Methods: {code['methods']:,}")
        lines.append(f"  - Public: {code['public_elements']:,} ({code['public_elements']/code['total_elements']*100:.1f}%)")
        lines.append(f"  - With docstrings: {code['with_docstrings']:,} ({code['with_docstrings']/code['total_elements']*100:.1f}%)")
        lines.append(f"  - Avg complexity: {code['avg_complexity']:.2f}\n")
        
        # File statistics
        files = summary["files"]
        lines.append(f"**Files:** {files['total']:,}")
        lines.append(f"  - Python files: {files['python']:,}\n")
        
        # Size statistics
        size = summary["size"]
        size_mb = size['total_bytes'] / (1024 * 1024)
        lines.append(f"**Size:**")
        lines.append(f"  - Total: {size_mb:.1f} MB")
        lines.append(f"  - Lines of code: {size['total_lines']:,}\n")
        
        # Documentation
        docs = summary["documentation"]
        lines.append(f"**Documentation:** {docs['sections']:,} sections\n")
        
        # Examples
        examples = summary["examples"]
        lines.append(f"**Examples:** {examples['total']:,}")
        
        return "\n".join(lines)


# Global analytics manager instance
_analytics_manager: Optional[AnalyticsManager] = None


def get_analytics_manager() -> AnalyticsManager:
    """Get or create the global analytics manager instance."""
    global _analytics_manager
    
    if _analytics_manager is None:
        _analytics_manager = AnalyticsManager()
    
    return _analytics_manager