"""
Enhanced relationship query handler using AST-based analysis.

This module provides advanced relationship queries using the enhanced
relationship data generated by generate_enhanced_relationships.py.
"""

import json
from pathlib import Path
from typing import Dict, List, Optional, Any, Set, Tuple
from collections import defaultdict

from loguru import logger

from advisor.config import settings


class EnhancedRelationshipQueryHandler:
    """Handles queries about code relationships using enhanced AST data."""
    
    def __init__(self, cache_dir: Optional[Path] = None):
        """Initialize enhanced relationship query handler."""
        self.cache_dir = cache_dir or settings.advisor_cache_dir
        self.data: Optional[Dict[str, Any]] = None
        self.modules_by_name: Dict[str, Dict[str, Any]] = {}
        self.load_data()
    
    def load_data(self):
        """Load enhanced relationship data from cache."""
        data_file = self.cache_dir / "enhanced_relationships.json"
        
        if not data_file.exists():
            logger.warning(f"Enhanced relationships file not found: {data_file}")
            return
        
        logger.info(f"Loading enhanced relationships from {data_file}")
        
        with open(data_file, 'r') as f:
            self.data = json.load(f)
        
        # Build module lookup
        for module in self.data.get('modules', []):
            module_name = module['module']
            self.modules_by_name[module_name] = module
            # Also index by short name
            short_name = module_name.split('.')[-1]
            if short_name not in self.modules_by_name:
                self.modules_by_name[short_name] = module
        
        logger.success(f"Loaded {len(self.data.get('modules', []))} modules with enhanced relationships")
    
    def find_module(self, name: str) -> Optional[Dict[str, Any]]:
        """Find a module by name (exact or partial match)."""
        name_lower = name.lower()
        
        # Try exact match
        if name_lower in self.modules_by_name:
            return self.modules_by_name[name_lower]
        
        # Try partial match
        for module_name, module_data in self.modules_by_name.items():
            if name_lower in module_name.lower():
                return module_data
        
        return None
    
    def find_class(self, name: str) -> Optional[Dict[str, Any]]:
        """Find a class by name across all modules."""
        name_lower = name.lower()
        
        for module in self.data.get('modules', []):
            for cls in module.get('classes', []):
                if cls['name'].lower() == name_lower:
                    return {
                        'class': cls,
                        'module': module['module'],
                        'file': module['file']
                    }
        
        return None
    
    def find_function(self, name: str) -> Optional[Dict[str, Any]]:
        """Find a function by name across all modules."""
        name_lower = name.lower()
        
        for module in self.data.get('modules', []):
            # Check module-level functions
            for func in module.get('functions', []):
                if func['name'].lower() == name_lower:
                    return {
                        'function': func,
                        'module': module['module'],
                        'file': module['file']
                    }
            
            # Check class methods
            for cls in module.get('classes', []):
                for method in cls.get('methods', []):
                    if method['name'].lower() == name_lower:
                        return {
                            'function': method,
                            'class': cls['name'],
                            'module': module['module'],
                            'file': module['file']
                        }
        
        return None
    
    def get_module_imports(self, module_name: str) -> List[Dict[str, Any]]:
        """Get all imports for a module."""
        module = self.find_module(module_name)
        if not module:
            return []
        
        return module.get('imports', [])
    
    def get_module_dependencies(self, module_name: str) -> Set[str]:
        """Get all module dependencies (imported modules)."""
        imports = self.get_module_imports(module_name)
        dependencies = set()
        
        for imp in imports:
            if imp['type'] == 'import':
                dependencies.add(imp['module'])
            elif imp['type'] == 'from_import':
                dependencies.add(imp['module'])
        
        return dependencies
    
    def get_class_hierarchy(self, class_name: str) -> Dict[str, Any]:
        """Get inheritance hierarchy for a class."""
        class_info = self.find_class(class_name)
        if not class_info:
            return {'found': False, 'reason': f'Class {class_name} not found'}
        
        cls = class_info['class']
        
        # Get base classes
        bases = cls.get('bases', [])
        
        # Find subclasses
        subclasses = []
        for module in self.data.get('modules', []):
            for other_cls in module.get('classes', []):
                if class_name in other_cls.get('bases', []):
                    subclasses.append({
                        'name': other_cls['name'],
                        'module': module['module']
                    })
        
        return {
            'found': True,
            'class': cls['name'],
            'module': class_info['module'],
            'bases': bases,
            'subclasses': subclasses,
            'methods': [m['name'] for m in cls.get('methods', [])]
        }
    
    def get_function_calls(self, function_name: str) -> Dict[str, Any]:
        """Get all function calls made by a function."""
        func_info = self.find_function(function_name)
        if not func_info:
            return {'found': False, 'reason': f'Function {function_name} not found'}
        
        # Find the module containing this function
        module = self.find_module(func_info['module'])
        if not module:
            return {'found': False, 'reason': 'Module not found'}
        
        # Get calls from this function
        calls = []
        for call in module.get('calls', []):
            caller = call['caller']
            # Check if this call is from our function
            if function_name in caller:
                calls.append(call)
        
        return {
            'found': True,
            'function': function_name,
            'module': func_info['module'],
            'calls': calls,
            'call_count': len(calls)
        }
    
    def get_callers(self, function_name: str) -> Dict[str, Any]:
        """Find all functions that call a given function."""
        callers = []
        
        for module in self.data.get('modules', []):
            for call in module.get('calls', []):
                if function_name in call['callee']:
                    callers.append({
                        'caller': call['caller'],
                        'module': module['module'],
                        'line': call['line']
                    })
        
        return {
            'function': function_name,
            'callers': callers,
            'caller_count': len(callers)
        }
    
    def get_circular_imports(self) -> List[List[str]]:
        """Get list of circular import chains."""
        return self.data.get('metrics', {}).get('circular_imports', [])
    
    def get_most_dependent_modules(self, limit: int = 10) -> List[Tuple[str, int]]:
        """Get modules with most dependencies."""
        return self.data.get('metrics', {}).get('most_dependent_modules', [])[:limit]
    
    def answer_query(self, query: str) -> str:
        """Answer a natural language query about relationships."""
        if not self.data:
            return "Enhanced relationship data not loaded. Please run generate_enhanced_relationships.py first."
        
        query_lower = query.lower()
        
        # Module import queries
        if "what does" in query_lower and "import" in query_lower:
            # Extract module name
            name = query_lower.replace("what does", "").replace("import", "").strip().rstrip("?")
            deps = self.get_module_dependencies(name)
            
            if deps:
                deps_list = "\n".join([f"  - {d}" for d in sorted(deps)[:20]])
                more = f"\n  ... and {len(deps) - 20} more" if len(deps) > 20 else ""
                return f"**{name}** imports {len(deps)} modules:\n\n{deps_list}{more}"
            else:
                return f"**{name}** does not import any modules, or module not found."
        
        # Class hierarchy queries
        if "what classes inherit from" in query_lower or "what extends" in query_lower:
            name = query_lower.replace("what classes inherit from", "").replace("what extends", "").strip().rstrip("?")
            hierarchy = self.get_class_hierarchy(name)
            
            if hierarchy.get('found'):
                if hierarchy['subclasses']:
                    subclasses_list = "\n".join([f"  - {s['name']} (in {s['module']})" for s in hierarchy['subclasses']])
                    return f"**{len(hierarchy['subclasses'])} classes** inherit from **{name}**:\n\n{subclasses_list}"
                else:
                    return f"No classes inherit from **{name}**."
            else:
                return hierarchy.get('reason', f'Class {name} not found')
        
        if "what does" in query_lower and "inherit from" in query_lower:
            name = query_lower.replace("what does", "").replace("inherit from", "").strip().rstrip("?")
            hierarchy = self.get_class_hierarchy(name)
            
            if hierarchy.get('found'):
                if hierarchy['bases']:
                    bases_list = "\n".join([f"  - {b}" for b in hierarchy['bases']])
                    return f"**{name}** inherits from:\n\n{bases_list}"
                else:
                    return f"**{name}** does not inherit from any base classes."
            else:
                return hierarchy.get('reason', f'Class {name} not found')
        
        # Function call queries
        if "what does" in query_lower and "call" in query_lower:
            name = query_lower.replace("what does", "").replace("call", "").strip().rstrip("?")
            result = self.get_function_calls(name)
            
            if result.get('found'):
                if result['call_count'] > 0:
                    calls_list = "\n".join([f"  - {c['callee']} (line {c['line']})" for c in result['calls'][:15]])
                    more = f"\n  ... and {result['call_count'] - 15} more" if result['call_count'] > 15 else ""
                    return f"**{name}** makes {result['call_count']} function calls:\n\n{calls_list}{more}"
                else:
                    return f"**{name}** does not make any function calls."
            else:
                return result.get('reason', f'Function {name} not found')
        
        if "what calls" in query_lower:
            name = query_lower.replace("what calls", "").strip().rstrip("?")
            result = self.get_callers(name)
            
            if result['caller_count'] > 0:
                callers_list = "\n".join([f"  - {c['caller']} (line {c['line']})" for c in result['callers'][:15]])
                more = f"\n  ... and {result['caller_count'] - 15} more" if result['caller_count'] > 15 else ""
                return f"**{name}** is called by {result['caller_count']} functions:\n\n{callers_list}{more}"
            else:
                return f"**{name}** is not called by any functions, or function not found."
        
        # Circular import queries
        if "circular import" in query_lower:
            cycles = self.get_circular_imports()
            if cycles:
                cycles_list = "\n\n".join([f"**Cycle {i+1}:** {' → '.join(cycle)}" for i, cycle in enumerate(cycles[:5])])
                more = f"\n\n... and {len(cycles) - 5} more cycles" if len(cycles) > 5 else ""
                return f"Found **{len(cycles)} circular import chains**:\n\n{cycles_list}{more}"
            else:
                return "✓ No circular imports detected in the codebase."
        
        # Most dependent modules
        if "most dependent" in query_lower or "most imports" in query_lower:
            modules = self.get_most_dependent_modules(10)
            if modules:
                modules_list = "\n".join([f"  {i+1}. **{m[0]}**: {m[1]} imports" for i, m in enumerate(modules)])
                return f"**Top 10 most dependent modules:**\n\n{modules_list}"
            else:
                return "No dependency data available."
        
        # Statistics
        if "how many" in query_lower:
            metrics = self.data.get('metrics', {})
            if "module" in query_lower:
                return f"The codebase has **{metrics.get('total_modules', 0)} modules**."
            elif "class" in query_lower:
                return f"The codebase has **{metrics.get('total_classes', 0)} classes**."
            elif "function" in query_lower:
                return f"The codebase has **{metrics.get('total_functions', 0)} functions**."
            elif "import" in query_lower:
                return f"The codebase has **{metrics.get('total_imports', 0)} import statements**."
            elif "call" in query_lower:
                return f"The codebase has **{metrics.get('total_calls', 0)} function calls**."
        
        return "I don't understand that query. Try asking:\n- 'What does X import?'\n- 'What classes inherit from X?'\n- 'What does X call?'\n- 'What calls X?'\n- 'Are there any circular imports?'\n- 'What are the most dependent modules?'"


# Singleton instance
_enhanced_handler: Optional[EnhancedRelationshipQueryHandler] = None


def get_enhanced_relationship_handler() -> EnhancedRelationshipQueryHandler:
    """Get or create singleton enhanced relationship handler."""
    global _enhanced_handler
    if _enhanced_handler is None:
        _enhanced_handler = EnhancedRelationshipQueryHandler()
    return _enhanced_handler