"""Work out which pages of a project's website are worth ingesting.

Pure logic plus one optional fetch, kept out of WebsiteIngestionSurveyor so the
judgement calls below can be tested without network.

Three site shapes showed up the moment this was tried against real projects, and
they need different handling. Guessing between them is the whole problem:

1. **Sitemap, versioned.** openlineage.io publishes a sitemap with 2,460 URLs, of
   which 2,398 are docs — but those are the *same* ~220 pages repeated across ten
   released versions plus `next`. Ingesting them all embeds ten near-identical
   copies of every passage, so a query matches a dozen versions of the same text
   and the LLM has no basis for choosing. The chunk count looks impressive and
   retrieval gets worse. Measured 2026-08-20.

2. **Sitemap, unversioned.** Ingest what the sitemap lists.

3. **The site is built from a repo we already ingest.** egeria-project.org is
   generated by the `egeria-docs` repo, which contains `site/mkdocs.yml` and
   `site/docs/CNAME` — and which Resource Explorer already registers and ingests
   as a repo. Fetching the rendered site would embed the same content twice, in a
   worse form (HTML boilerplate instead of source markdown). Worse, four
   registered repos declare that same homepage, so a naive per-repo ingest would
   embed it four times over.

Only the last of those is a "do nothing" answer, and it is the one most likely to
be missed, because the ingest itself would succeed and look productive.
"""
from __future__ import annotations

import logging
import re
from urllib.parse import urljoin, urlparse

log = logging.getLogger(__name__)

# Files whose presence in a repo means that repo *builds* a website. Checked
# against the repo's own file inventory, at any depth — egeria-docs keeps its
# mkdocs.yml under site/, not at the root.
_SITE_GENERATOR_MARKERS = (
    "mkdocs.yml", "mkdocs.yaml",          # MkDocs (Egeria)
    "docusaurus.config.js", "docusaurus.config.ts",  # Docusaurus (OpenLineage)
    "_config.yml",                          # Jekyll / GitHub Pages
    "conf.py",                              # Sphinx — noisy, see _is_sphinx_conf
    "book.toml",                            # mdBook
    "CNAME",                                # custom domain for GitHub Pages
)

# A version segment in a docs path: 1.44.0, v2, 2.1, next, latest, stable.
_VERSION_SEGMENT = re.compile(r"^(v?\d+(\.\d+)*|next|latest|stable|dev|main)$", re.I)

# Segments that are documentation rather than marketing/news. A site's blog is
# usually a poor ingestion target — announcements age badly and crowd out the
# reference material a question is actually about.
_DOC_HINTS = ("/docs/", "/documentation/", "/guide/", "/guides/", "/reference/", "/api/")
_SKIP_HINTS = ("/blog/", "/news/", "/authors/", "/tags/", "/archive/", "/search")


def _is_sphinx_conf(path: str) -> bool:
    """conf.py is a common filename; only treat it as a site marker when it sits
    somewhere docs-shaped, or every Python repo looks like a website."""
    p = path.lower()
    return p.endswith("conf.py") and ("doc" in p or "sphinx" in p)


# Hosts that are a code forge, not a documentation site. A repo whose declared
# homepage points back at its own forge page has no docs site — HomepageSurveyor
# falls back to the README/manifest URLs and those sometimes *are* the repo URL
# (measured: kedro_plugins). Ingesting anyway would embed the forge's own UI
# chrome — file listings, nav, sign-in prompts — as if it were documentation,
# and those pages match almost any query while answering none of them.
_CODE_HOSTS = ("github.com", "gitlab.com", "bitbucket.org", "codeberg.org",
               "sourceforge.net", "git.sr.ht")


def is_code_host(url: str) -> bool:
    """True when this URL is a forge page rather than a documentation site.

    Checked on the host, not the full URL, so a project's own docs hosted *by*
    a forge (github.io / gitlab.io pages) is correctly not treated as a forge
    page — that is a real published site and the one thing this must not
    exclude, since it is how a large share of projects publish docs at all.
    """
    host = (urlparse(url).hostname or "").lower().removeprefix("www.")
    return host in _CODE_HOSTS


def repo_publishes_site(file_inventory: list[str]) -> str:
    """If this repo builds a website, return the marker that says so, else "".

    Callers should treat a non-empty result as "do not ingest the rendered site"
    — the source is already being ingested as a repo, in a better form.
    """
    for path in file_inventory:
        name = path.rsplit("/", 1)[-1]
        if name in _SITE_GENERATOR_MARKERS and name != "conf.py":
            return path
        if _is_sphinx_conf(path):
            return path
    return ""


def collapse_versioned(urls: list[str]) -> list[str]:
    """Drop older copies of versioned documentation, keeping one set.

    Docusaurus and friends publish /docs/<version>/<page> for every release. The
    pages differ only in version, so embedding them all is straightforwardly
    harmful to retrieval (see module docstring). This keeps the highest numeric
    version, and drops `next`/`dev`/`main` in favour of it — a released version
    is what a user asking a question is running.

    URLs with no version segment are always kept: unversioned sites are shape 2,
    and a site mixing both (openlineage.io has /docs/1.50.0/... *and*
    /docs/spec/...) needs its unversioned pages preserved.
    """
    versioned: dict[tuple, dict[str, str]] = {}
    plain: list[str] = []

    for url in urls:
        parts = [p for p in urlparse(url).path.split("/") if p]
        # A version segment must be a *directory* — /docs/1.50.0/page — not the
        # last segment. Otherwise an ordinary numbered page (/docs/chapter/1, or
        # a paginated /docs/9) reads as a version and every such page in a
        # section collapses into one, silently dropping the rest. Caught by test
        # rather than by inspection.
        idx = next((i for i, p in enumerate(parts[:-1]) if _VERSION_SEGMENT.match(p)), None)
        if idx is None:
            plain.append(url)
            continue
        # Key on everything except the version segment, so the same page across
        # versions collapses to one entry.
        key = (tuple(parts[:idx]), tuple(parts[idx + 1:]))
        versioned.setdefault(key, {})[parts[idx]] = url

    def _rank(v: str) -> tuple:
        # Numeric releases sort above the moving pointers, which are a preview of
        # a release nobody is running yet.
        if _VERSION_SEGMENT.match(v) and v[0].isdigit() or v.lower().startswith("v"):
            nums = [int(n) for n in re.findall(r"\d+", v)] or [0]
            return (1, nums)
        return (0, [0])

    kept = [sorted(byver.items(), key=lambda kv: _rank(kv[0]))[-1][1]
            for byver in versioned.values()]
    return plain + kept


def filter_doc_pages(urls: list[str]) -> list[str]:
    """Keep documentation, drop blog/news/tag pages.

    If nothing looks doc-shaped, return everything rather than nothing — a small
    project site with no /docs/ prefix is still worth ingesting, and returning an
    empty list here would look like a fetch failure rather than a filter result.
    """
    docs = [u for u in urls if any(h in u.lower() for h in _DOC_HINTS)
            and not any(s in u.lower() for s in _SKIP_HINTS)]
    if docs:
        return docs
    return [u for u in urls if not any(s in u.lower() for s in _SKIP_HINTS)]


def parse_sitemap(xml: str, base_url: str = "") -> list[str]:
    """URLs from a sitemap. Handles a sitemap index by returning the child
    sitemap URLs, which the caller fetches in turn."""
    locs = re.findall(r"<loc>\s*([^<\s]+)\s*</loc>", xml or "", re.I)
    return [urljoin(base_url, u) if base_url else u for u in locs]


def is_sitemap_index(xml: str) -> bool:
    return "<sitemapindex" in (xml or "").lower()


_META_REFRESH = re.compile(
    r"""<meta[^>]+http-equiv=["']?refresh["']?[^>]*content=["'][^"']*url=([^"'\s>]+)""",
    re.I)


def follow_meta_refresh(html: str, base_url: str) -> str | None:
    """The target of a `<meta http-equiv="refresh">` landing page, if it is one.

    urllib follows HTTP redirects but not this one, so a site whose entry point
    is a meta-refresh stub reads as a page that fetched fine and simply had no
    content — the ingest reports success having embedded nothing. Measured on
    sqlglot.com, a 138-byte stub pointing at ./sqlglot.html; pdoc generates this
    shape by default, so it is a family of sites rather than one project's quirk.
    """
    m = _META_REFRESH.search(html or "")
    if not m:
        return None
    target = urljoin(base_url, m.group(1).strip())
    # Only within the same site: a redirect off-host is a different project's
    # documentation, not this one's.
    return target if urlparse(target).netloc == urlparse(base_url).netloc else None


def discover_pages(base_url: str, fetch, max_pages: int = 400) -> tuple[list[str], str]:
    """Return (page urls, how they were found).

    fetch(url) -> str|None. Tries the site's sitemap first; falls back to the
    single page when there is none, which is the honest answer for a site that
    publishes no index rather than a reason to start crawling links.

    max_pages caps the result. A docs site is worth ingesting; an unbounded crawl
    of someone else's website is not something a survey step should do.
    """
    root = f"{urlparse(base_url).scheme}://{urlparse(base_url).netloc}"
    for candidate in (urljoin(root + "/", "sitemap.xml"), urljoin(base_url.rstrip("/") + "/", "sitemap.xml")):
        xml = fetch(candidate)
        if not xml or "<loc" not in xml.lower():
            continue
        urls = parse_sitemap(xml, candidate)
        if is_sitemap_index(xml):
            child: list[str] = []
            for sm in urls[:20]:          # bounded: an index of hundreds is a crawl
                sub = fetch(sm)
                if sub:
                    child.extend(parse_sitemap(sub, sm))
            urls = child or urls
        # Same host only — a sitemap can legitimately list other domains.
        host = urlparse(base_url).netloc
        urls = [u for u in urls if urlparse(u).netloc == host]
        pages = collapse_versioned(filter_doc_pages(urls))
        if pages:
            return sorted(pages)[:max_pages], f"sitemap ({candidate})"
    # No sitemap: the page itself is the answer — unless it is a meta-refresh
    # stub, in which case the real page is one hop away and the stub has no
    # content at all.
    html = fetch(base_url)
    target = follow_meta_refresh(html or "", base_url)
    if target:
        return [target], "single page (meta-refresh from no-sitemap landing page)"
    return [base_url], "single page (no sitemap)"

def site_collection_name(url: str) -> str:
    """Collection name for a website, derived from its host — NOT from a repo slug.

    A project's website belongs to the *project*, not to any one of its
    repositories. In this deployment four registered repos (egeria_git,
    egeria_docs, egeria_python_git, trellis) all declare
    https://egeria-project.org, and they are all in the same `egeria` group. A
    per-repo collection would embed that one site four times, and a question
    routed to any one repo would miss the other three copies for no reason.

    Keying on the host means the site is ingested once and every repo pointing at
    it can list the same collection, so the query router searches it whichever
    repo the user is looking at. Host rather than group slug because the homepage
    is the thing actually being fetched — two groups can legitimately share a
    site, and a group can be renamed without invalidating an ingest.
    """
    from urllib.parse import urlparse

    host = (urlparse(url).hostname or "").lower().removeprefix("www.")
    return "web_docs_" + re.sub(r"[^a-z0-9]+", "_", host).strip("_")

def site_richness(base_url: str, fetch) -> dict:
    """How much documentation a candidate site actually has, and how fresh.

    A project can have more than one plausible docs URL — docling publishes both
    docling.ai and docling-project.github.io/docling, and the two are not
    equivalent. Measured 2026-08-20: docling.ai's sitemap lists 16 pages with
    lastmod 2026-08-19, while the github.io sitemap returned one byte. Preferring
    whichever URL a manifest happened to mention first would have picked the dead
    one roughly half the time.

    Returns {pages, newest, reachable}. `newest` is the newest <lastmod> in the
    sitemap, which is the only freshness signal a site reliably volunteers —
    fetching every page to compare content would cost more than the ingest.
    Absent lastmod, freshness is unknown rather than old.
    """
    root = f"{urlparse(base_url).scheme}://{urlparse(base_url).netloc}"
    for candidate in (urljoin(root + "/", "sitemap.xml"),
                      urljoin(base_url.rstrip("/") + "/", "sitemap.xml")):
        xml = fetch(candidate) or ""
        if "<loc" not in xml.lower():
            continue
        host = urlparse(base_url).netloc
        urls = [u for u in parse_sitemap(xml, candidate) if urlparse(u).netloc == host]
        pages = collapse_versioned(filter_doc_pages(urls))
        lastmods = sorted(re.findall(r"<lastmod>\s*([^<\s]+)", xml, re.I), reverse=True)
        return {"pages": len(pages), "newest": lastmods[0] if lastmods else "",
                "reachable": True, "sitemap": candidate}
    return {"pages": 0, "newest": "", "reachable": bool(fetch(base_url)), "sitemap": ""}


def pick_richest(candidates: list[str], fetch) -> tuple[str, dict]:
    """Choose the best documentation site from several candidate URLs.

    Ranked on page count first, then newest lastmod. Page count is the stronger
    signal: a site with ten times the pages is a different thing, whereas a few
    days' difference in lastmod usually means one of them rebuilt on a schedule.
    Ties fall back to the given order, which is the caller's own preference.
    """
    scored = []
    for url in candidates:
        if not url:
            continue
        try:
            scored.append((url, site_richness(url, fetch)))
        except Exception as exc:          # a dead candidate must not lose the live one
            log.debug("site_richness(%s) failed: %s", url, exc)
            scored.append((url, {"pages": 0, "newest": "", "reachable": False, "sitemap": ""}))
    if not scored:
        return "", {}
    best = max(scored, key=lambda kv: (kv[1]["pages"], kv[1]["newest"]))
    return best[0], best[1]
