"""
Question checklist catalog — loaded from configdata/question_catalog.yaml,
generated by scripts/csv_to_question_catalog_yaml.py from
docs/dr-egeria/resource_questions.csv (the source of truth for both that
YAML and the Dr.Egeria markdown processed into Egeria itself — see
docs/dr-egeria/foundations.md).

Backs the Scouting "Questions" checklist tab: for a given resource, which
of the authored Scouting questions are answerable today (and by which
analysis_catalog.yaml analysis), which are gaps, and which need a human via
Enrichment — filterable by the same Perspective set used elsewhere in the
UI.

`purposes` carries the Purpose kinds a question serves (2026-08-24). Purpose
is the PRIMARY dispatch axis, Perspective the secondary one — measured over
the whole catalog, no Perspective reaches an analysis that another Perspective
doesn't also reach, so Perspective can rank but cannot select. Purpose orders
what runs by default; it never excludes.

`answering.checks` carries the finer `analysis_id:check_name` join added
2026-08-24, alongside `analysis_ids` rather than replacing it. Several
analyses bundle unrelated checks — `repo_conventions` alone answers 7 of the
16 analysis-answerable questions across its 5 checks — so an analysis-level
join loses most of the information the question corpus actually carries.
Valid check names are declared in configdata/check_registry.yaml; note that
`findings_kind` there is not always the analysis id. `checks` is empty for
questions answered by a whole analysis with no per-check decomposition, and
for every question whose CSV row has not been given check refs yet, so
consumers must treat empty as "fall back to analysis_ids", never as "no
checks apply". Mirrors analysis_catalog_reader.py's loading convention exactly
(frozen dataclass, lru_cache-backed loader, clear_cache() testing hook).

This module does NOT read Egeria live — the YAML (ultimately the CSV) is
the source of truth for now, matching how csv_to_dr_egeria_questions.py's
own output is also generated rather than read back from Egeria. A future
pass could query Egeria's real Question/Perspective/ScopedBy elements
directly (see docs/dr-egeria/foundations.md's header comment on the
Unification Thread) — deliberately not built yet.
"""
from __future__ import annotations

import functools
from dataclasses import dataclass, field
from pathlib import Path

import yaml

_DEFAULT_CONFIG_PATH = Path(__file__).parent.parent / "configdata" / "question_catalog.yaml"


@dataclass(frozen=True)
class QuestionAnswering:
    kind: str  # analysis | direct | registry | human | chart | gap | partial | mixed | unknown
    analysis_ids: list[str] = field(default_factory=list)
    checks: list[str] = field(default_factory=list)
    note: str = ""

    def to_dict(self) -> dict:
        return {"kind": self.kind, "analysis_ids": self.analysis_ids,
                "checks": self.checks, "note": self.note}


@dataclass(frozen=True)
class QuestionCatalogEntry:
    question: str
    stage: str
    perspectives: list[str]
    answering: QuestionAnswering
    purposes: list[str] = field(default_factory=list)
    answering_mechanism: str = ""

    def to_dict(self) -> dict:
        return {
            "question": self.question,
            "stage": self.stage,
            "perspectives": self.perspectives,
            "purposes": self.purposes,
            "answering": self.answering.to_dict(),
            "answering_mechanism": self.answering_mechanism,
        }


def _entry_from_yaml(raw: dict) -> QuestionCatalogEntry:
    answering_raw = raw.get("answering") or {}
    return QuestionCatalogEntry(
        question=raw["question"],
        stage=raw.get("stage", ""),
        perspectives=list(raw.get("perspectives") or []),
        purposes=list(raw.get("purposes") or []),
        answering=QuestionAnswering(
            kind=answering_raw.get("kind", "unknown"),
            analysis_ids=list(answering_raw.get("analysis_ids") or []),
            checks=list(answering_raw.get("checks") or []),
            note=answering_raw.get("note", ""),
        ),
        answering_mechanism=raw.get("answering_mechanism", ""),
    )


@functools.lru_cache(maxsize=1)
def _load(config_path: Path = _DEFAULT_CONFIG_PATH) -> dict[str, list[QuestionCatalogEntry]]:
    if not config_path.exists():
        return {"repo": []}
    with open(config_path) as f:
        raw = yaml.safe_load(f) or {}

    return {
        "repo": [_entry_from_yaml(e) for e in raw.get("repo_questions") or []],
    }


def clear_cache() -> None:
    """Testing hook — the loader result is cached via lru_cache."""
    _load.cache_clear()


def get_questions(
    resource_type: str = "repo",
    phase: str | None = None,
    perspectives: list[str] | None = None,
    purposes: list[str] | None = None,
) -> list[dict]:
    """Return question catalog entries for a resource type, optionally
    filtered by funnel-stage phase and/or Perspective set, and optionally
    ORDERED by Purpose.

    phase: matched against the entry's (single) `stage` field
    (case-insensitive). A stage may be slash-combined (e.g.
    "Analysis/Enrichment", signaling an Analysis-first/Enrichment-fallback
    pattern — see docs/confidence-gated-validation-plan.md) — matches if
    `phase` equals ANY of the slash-separated parts, not just the whole
    string, so a question tagged "Analysis/Enrichment" shows up under both
    Analysis's and Enrichment's checklist.

    perspectives: OR-matched against each entry's perspectives list, same
    semantics as analysis_catalog_reader.get_analyses()'s perspective
    filter and the UI's activePerspectives multi-select — empty/None means
    no filter (show everything for the phase).

    purposes: **ORDERS, never excludes.** Entries serving any of the given
    Purposes sort first; everything else follows in catalog order. This is
    the asymmetry measured in docs/investigation-framing-design.md §3 —
    Purpose discriminates (overlap 0.22) and Perspective does not (0.37,
    strictly nested sets), so Perspective filters what is *shown* while
    Purpose ranks what comes *first*. Filtering on Purpose here would be a
    bug: nothing is hidden by it. Empty/None leaves catalog order untouched.

    Every returned entry carries a `derivation` key recording why it is in
    the result — which Perspectives and Purposes matched, and whether
    Purpose promoted it. That chain (Purpose + Perspective → question →
    analysis_ids) is the explanation a user actually asks for, and it is
    already implicit in this function; `derivation` just stops discarding
    it. See docs/context-compilation-design.md §11.
    """
    entries = [e.to_dict() for e in _load().get(resource_type, [])]

    if phase:
        phase_lower = phase.lower()
        entries = [
            e for e in entries
            if phase_lower in {part.strip().lower() for part in e["stage"].split("/")}
        ]

    if perspectives:
        wanted = {p.lower() for p in perspectives}
        entries = [
            e for e in entries
            if wanted.intersection(p.lower() for p in e["perspectives"])
        ]

    wanted_persp = {p.lower() for p in (perspectives or [])}
    wanted_purp = {p.lower() for p in (purposes or [])}

    for e in entries:
        matched_persp = [p for p in e["perspectives"] if p.lower() in wanted_persp]
        matched_purp = [p for p in e["purposes"] if p.lower() in wanted_purp]
        e["derivation"] = {
            "phase": phase or "",
            "matched_perspectives": matched_persp,
            "matched_purposes": matched_purp,
            "purpose_ranked": bool(matched_purp),
            "analysis_ids": list(e["answering"]["analysis_ids"]),
            "checks": list(e["answering"]["checks"]),
        }

    if wanted_purp:
        # Stable: promoted entries keep catalog order among themselves, and
        # so does everything else. Nothing is dropped.
        entries.sort(key=lambda e: not e["derivation"]["purpose_ranked"])

    return entries
