"""
Question checklist catalog — loaded from configdata/question_catalog.yaml,
generated by scripts/csv_to_question_catalog_yaml.py from
docs/dr-egeria/resource_questions.csv (the source of truth for both that
YAML and the Dr.Egeria markdown processed into Egeria itself — see
docs/dr-egeria/foundations.md).

Backs the Scouting "Questions" checklist tab: for a given resource, which
of the authored Scouting questions are answerable today (and by which
analysis_catalog.yaml analysis), which are gaps, and which need a human via
Enrichment — filterable by the same Perspective set used elsewhere in the
UI. Mirrors analysis_catalog_reader.py's loading convention exactly
(frozen dataclass, lru_cache-backed loader, clear_cache() testing hook).

This module does NOT read Egeria live — the YAML (ultimately the CSV) is
the source of truth for now, matching how csv_to_dr_egeria_questions.py's
own output is also generated rather than read back from Egeria. A future
pass could query Egeria's real Question/Perspective/ScopedBy elements
directly (see docs/dr-egeria/foundations.md's header comment on the
Unification Thread) — deliberately not built yet.
"""
from __future__ import annotations

import functools
from dataclasses import dataclass, field
from pathlib import Path

import yaml

_DEFAULT_CONFIG_PATH = Path(__file__).parent.parent / "configdata" / "question_catalog.yaml"


@dataclass(frozen=True)
class QuestionAnswering:
    kind: str  # analysis | direct | registry | human | chart | gap | partial | mixed | unknown
    analysis_ids: list[str] = field(default_factory=list)
    note: str = ""

    def to_dict(self) -> dict:
        return {"kind": self.kind, "analysis_ids": self.analysis_ids, "note": self.note}


@dataclass(frozen=True)
class QuestionCatalogEntry:
    question: str
    stage: str
    perspectives: list[str]
    answering: QuestionAnswering
    answering_mechanism: str = ""

    def to_dict(self) -> dict:
        return {
            "question": self.question,
            "stage": self.stage,
            "perspectives": self.perspectives,
            "answering": self.answering.to_dict(),
            "answering_mechanism": self.answering_mechanism,
        }


def _entry_from_yaml(raw: dict) -> QuestionCatalogEntry:
    answering_raw = raw.get("answering") or {}
    return QuestionCatalogEntry(
        question=raw["question"],
        stage=raw.get("stage", ""),
        perspectives=list(raw.get("perspectives") or []),
        answering=QuestionAnswering(
            kind=answering_raw.get("kind", "unknown"),
            analysis_ids=list(answering_raw.get("analysis_ids") or []),
            note=answering_raw.get("note", ""),
        ),
        answering_mechanism=raw.get("answering_mechanism", ""),
    )


@functools.lru_cache(maxsize=1)
def _load(config_path: Path = _DEFAULT_CONFIG_PATH) -> dict[str, list[QuestionCatalogEntry]]:
    if not config_path.exists():
        return {"repo": []}
    with open(config_path) as f:
        raw = yaml.safe_load(f) or {}

    return {
        "repo": [_entry_from_yaml(e) for e in raw.get("repo_questions") or []],
    }


def clear_cache() -> None:
    """Testing hook — the loader result is cached via lru_cache."""
    _load.cache_clear()


def get_questions(
    resource_type: str = "repo",
    phase: str | None = None,
    perspectives: list[str] | None = None,
) -> list[dict]:
    """Return question catalog entries for a resource type, optionally
    filtered by funnel-stage phase and/or Perspective set.

    phase: matched against the entry's (single) `stage` field
    (case-insensitive). A stage may be slash-combined (e.g.
    "Analysis/Enrichment", signaling an Analysis-first/Enrichment-fallback
    pattern — see docs/confidence-gated-validation-plan.md) — matches if
    `phase` equals ANY of the slash-separated parts, not just the whole
    string, so a question tagged "Analysis/Enrichment" shows up under both
    Analysis's and Enrichment's checklist.

    perspectives: OR-matched against each entry's perspectives list, same
    semantics as analysis_catalog_reader.get_analyses()'s perspective
    filter and the UI's activePerspectives multi-select — empty/None means
    no filter (show everything for the phase)."""
    entries = [e.to_dict() for e in _load().get(resource_type, [])]

    if phase:
        phase_lower = phase.lower()
        entries = [
            e for e in entries
            if phase_lower in {part.strip().lower() for part in e["stage"].split("/")}
        ]

    if perspectives:
        wanted = {p.lower() for p in perspectives}
        entries = [
            e for e in entries
            if wanted.intersection(p.lower() for p in e["perspectives"])
        ]

    return entries
