#!/usr/bin/env python3
"""Vendor the two /next fonts, the way build-vendor.js vendors the JS.

Cormorant Garamond and Lora, latin + latin-ext only, written into
`resource_explorer/web/static/next/fonts/` with a `fonts.css` whose `src`
URLs point at the local files. Nothing in this app loads an asset from a CDN
at runtime -- see frontend-build/README.md for why -- and the fonts the /next
skin needs are no exception.

Both families are served by Google as VARIABLE fonts: weight 400 and weight
600 resolve to the same woff2 per subset. The script dedupes on the URL, so
four files cover four faces. Downloading one file per (family, weight) would
double the payload for identical bytes.

    python3 frontend-build/build-next-fonts.py

Re-run only to pick up an upstream font revision; the output is checked in
like any other static asset.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

CSS2 = (
    "https://fonts.googleapis.com/css2"
    "?family=Cormorant+Garamond:wght@400;600&family=Lora:wght@400;600&display=swap"
)
# css2 serves woff2 @font-face blocks only to a browser UA; a plain curl UA
# gets the ttf fallback stylesheet instead.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)
SUBSETS = ("latin", "latin-ext")
OUT = Path(__file__).resolve().parent.parent / "resource_explorer/web/static/next/fonts"

HEADER = """/* Self-hosted subsets of Cormorant Garamond and Lora (latin, latin-ext).
   GENERATED by frontend-build/build-next-fonts.py -- do not hand-edit.

   Both families are variable fonts upstream, so one file per subset serves
   both the 400 and the 600 face; the duplicate @font-face blocks below
   deliberately share a src. */

"""


def main() -> int:
    src = subprocess.run(
        ["curl", "-sS", "-A", UA, CSS2], capture_output=True, text=True, check=True
    ).stdout
    if "woff2" not in src:
        print("css2 returned no woff2 faces -- check the User-Agent", file=sys.stderr)
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    kept: list[str] = []
    downloads: dict[str, str] = {}  # local filename -> url

    for block in re.split(r"(?=/\* [a-z\-]+ \*/)", src):
        subset = re.match(r"/\* ([a-z\-]+) \*/", block.strip())
        if not subset or subset.group(1) not in SUBSETS:
            continue
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        url = re.search(r"url\((https://[^)]+)\)", block).group(1)
        name = f"{family.replace(' ', '')}-{subset.group(1)}.woff2"
        downloads[name] = url
        kept.append(block.replace(url, f"./{name}"))

    for name, url in sorted(downloads.items()):
        subprocess.run(["curl", "-sS", "-o", str(OUT / name), url], check=True)
        print(f"  {name}")

    (OUT / "fonts.css").write_text(HEADER + "".join(kept))
    print(f"{len(downloads)} files + fonts.css -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
