#!/usr/bin/env python3
"""Vendor the Lucide icons /next uses, as one inline SVG sprite.

Emoji is not this UI's icon system — but the objection was always specific
(the same glyph used for two things, per-platform rendering, cannot be
recoloured to carry state, cannot be extended). It was never an objection to
pictograms. So each emoji is replaced by the NEAREST LUCIDE EQUIVALENT OF THE
SAME METAPHOR rather than by an abstract shape: a cloud stays a cloud.

Output is `static/next/icons.svg`, a sprite of `<symbol>` elements that
app.js injects into the document once at boot. Injected rather than
referenced as an external `<use href="file.svg#id">` because `currentColor`
does not inherit into an externally-referenced sprite in every browser, and
inheriting the surrounding colour is the entire point — these icons carry
state.

    python3 frontend-build/build-next-icons.py

Icons are MIT-licensed (lucide-icons/lucide). Pinned by version below.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

VERSION = "0.454.0"
BASE = f"https://cdn.jsdelivr.net/npm/lucide-static@{VERSION}/icons"
OUT = Path(__file__).resolve().parent.parent / "resource_explorer/web/static/next/icons.svg"

#: name -> what it replaces / what it is for.
ICONS = {
    "cloud": "published to Egeria (was the cloud emoji)",
    "bar-chart-2": "surveyed (was the bar-chart emoji)",
    "sparkles": "registered, not yet surveyed (was the sparkles emoji)",
    "thumbs-up": "feedback: helpful",
    "minus": "feedback: partly right",
    "thumbs-down": "feedback: not helpful",
    "external-link": "leaves the app",
    "eye": "disposition: tracking",
    "microscope": "disposition: investigating",
    "thumbs-up-check": "disposition: recommended",   # falls back below
    "check-circle-2": "disposition: using",
    "circle-slash": "hidden from the personal list",
    "panel-right-close": "close the chat drawer",
    "panel-right-open": "open the chat drawer",
    "maximize-2": "promote a rail answer into the pane",
}
#: Icons renamed or absent upstream, mapped to the nearest real one.
FALLBACK = {
    "thumbs-up-check": "badge-check",
    "check-circle-2": "circle-check",
    "bar-chart-2": "chart-column",
}


def fetch(name: str) -> str | None:
    url = f"{BASE}/{name}.svg"
    r = subprocess.run(["curl", "-sfS", url], capture_output=True, text=True)
    return r.stdout if r.returncode == 0 and "<svg" in r.stdout else None


def main() -> int:
    symbols = []
    for name in ICONS:
        svg = fetch(name)
        if svg is None and name in FALLBACK:
            print(f"  {name}: not found upstream, using {FALLBACK[name]}")
            svg = fetch(FALLBACK[name])
        if svg is None:
            print(f"  {name}: NOT FOUND — skipped", file=sys.stderr)
            continue
        inner = re.sub(r"(?s)^.*?<svg[^>]*>|</svg>\s*$", "", svg).strip()
        # Lucide's own stroke attributes live on the root <svg>; carry the
        # ones that matter onto the symbol so a bare <use> renders correctly.
        symbols.append(
            f'<symbol id="i-{name}" viewBox="0 0 24 24" fill="none" '
            f'stroke="currentColor" stroke-width="2" stroke-linecap="round" '
            f'stroke-linejoin="round">\n{inner}\n</symbol>'
        )
        print(f"  {name}")

    if not symbols:
        print("nothing fetched", file=sys.stderr)
        return 1

    OUT.write_text(
        f"<!-- GENERATED by frontend-build/build-next-icons.py — do not hand-edit.\n"
        f"     Lucide {VERSION}, MIT (lucide-icons/lucide). -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">\n'
        + "\n".join(symbols)
        + "\n</svg>\n"
    )
    print(f"{len(symbols)} symbols -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
