"""
Generate resource_explorer/configdata/question_catalog.yaml from the same
Scouting questions CSV that scripts/csv_to_dr_egeria_questions.py consumes
(docs/dr-egeria/scouting-questions.csv) — the CSV stays the single source
of truth for both outputs (Dr.Egeria markdown for Egeria itself, this YAML
for RE's own runtime "Questions" checklist).

Why a separate script rather than folding this into
csv_to_dr_egeria_questions.py: that script's whole job is producing
Dr.Egeria command blocks — this one produces a config file consumed by
Python at runtime (question_catalog_reader.py, matching
analysis_catalog_reader.py's loading convention). Different output,
different consumer, kept separate on purpose.

Parses the CSV's free-text "Answering Analysis" column into a light,
queryable structure (kind + analysis_ids + the original note text) rather
than requiring a second, redundant structured column in the CSV — the free
text already follows a consistent convention (GAP:/PARTIAL:/MIXED:/"N/A —"
prefixes, established when that column was authored) that a human keeps
writing naturally; this script just recognizes it.

Usage:
    uv run --package resource-explorer \\
        python packages/resource-explorer/scripts/csv_to_question_catalog_yaml.py \\
        docs/dr-egeria/scouting-questions.csv \\
        [--output resource_explorer/configdata/question_catalog.yaml]
"""
from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path

import yaml

# Real repo_analyses ids from configdata/analysis_catalog.yaml — kept as a
# literal list (not read live from that file) so this script has no import
# dependency on the resource_explorer package; re-sync by hand if that
# catalog's id set changes (rare — ids are stable identifiers by convention,
# see that file's own header comment).
KNOWN_ANALYSIS_IDS = [
    "language_file_classification",
    "repository_health",
    "dependency_analysis",
    "security_scan",
    "documentation_coverage",
    "license_classification",
    "security_features",
    "ci_quality",
    "maturity",
    "repo_conventions",
    "data_file_profiling",
    "api_structure",
    "repo_profile_refresh",
    "rag_ingestion",
    "egeria_publish",
]


def _parse_answering(note: str) -> dict:
    note = (note or "").strip()
    upper = note.upper()
    if upper.startswith("GAP:"):
        kind = "gap"
    elif upper.startswith("PARTIAL:"):
        kind = "partial"
    elif upper.startswith("MIXED:"):
        kind = "mixed"
    elif "human-supplied" in note.lower():
        kind = "human"
    elif "trend chart" in note.lower():
        kind = "chart"
    elif note.upper().startswith("N/A"):
        kind = "direct"
    elif note in KNOWN_ANALYSIS_IDS:
        kind = "analysis"
    else:
        # Free text that doesn't match any known convention — surfaced as
        # "unknown" rather than silently mis-tagged; a real gap in the CSV
        # authoring convention, not something to guess past.
        kind = "unknown"

    analysis_ids = [
        aid for aid in KNOWN_ANALYSIS_IDS
        if re.search(rf"\b{re.escape(aid)}\b", note)
    ]

    return {"kind": kind, "analysis_ids": analysis_ids, "note": note}


def generate(rows: list[dict]) -> str:
    entries = []
    for row in rows:
        question = (row.get("Question") or "").strip()
        if not question:
            continue
        perspective_cols = [
            c for c in row.keys()
            if c not in ("Question", "Asked At", "Answered At", "Why is this important?",
                          "Rationale/Source", "Answering Analysis")
        ]
        perspectives = [c for c in perspective_cols if (row.get(c) or "").strip()]

        entries.append({
            "question": question,
            "asked_at": (row.get("Asked At") or "").strip(),
            "answered_at": (row.get("Answered At") or "").strip(),
            "perspectives": perspectives,
            "answering": _parse_answering(row.get("Answering Analysis", "")),
        })

    header = (
        "# Question checklist catalog — generated by\n"
        "# scripts/csv_to_question_catalog_yaml.py from\n"
        "# docs/dr-egeria/scouting-questions.csv (the source of truth — edit that\n"
        "# CSV, then regenerate this file, don't hand-edit it directly). Backs the\n"
        "# Scouting \"Questions\" checklist tab (question_catalog_reader.py).\n"
        "#\n"
        "# Each entry:\n"
        "#   question      - display text; matches the Egeria GlossaryTerm Display\n"
        "#                   Name exactly (case+punctuation-sensitive) since it's\n"
        "#                   also the join key back to Egeria's own Question\n"
        "#                   elements, if/when RE ever queries them live.\n"
        "#   asked_at      - Funnel Stage this question is naturally raised at.\n"
        "#   answered_at   - Funnel Stage whose data can actually answer it.\n"
        "#   perspectives  - Perspective names this question is linked to.\n"
        "#   answering:\n"
        "#     kind        - \"analysis\" | \"direct\" | \"registry\" | \"human\" |\n"
        "#                   \"chart\" | \"gap\" | \"partial\" | \"mixed\" | \"unknown\" —\n"
        "#                   how (or whether) RE can answer this today.\n"
        "#     analysis_ids - analysis_catalog.yaml repo_analyses ids that answer\n"
        "#                   (fully or partially) this question; may be empty.\n"
        "#     note        - the CSV's \"Answering Analysis\" column, verbatim —\n"
        "#                   human-readable detail (candidate tooling for gaps,\n"
        "#                   which direct field/table, etc.).\n\n"
    )
    body = yaml.safe_dump({"repo_questions": entries}, sort_keys=False, allow_unicode=True, width=100)
    return header + body


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("csv_path", type=Path, help="Source CSV (see module docstring)")
    parser.add_argument(
        "--output", type=Path,
        default=Path(__file__).parent.parent / "resource_explorer" / "configdata" / "question_catalog.yaml",
        help="Output YAML path (default: resource_explorer/configdata/question_catalog.yaml)",
    )
    args = parser.parse_args()

    if not args.csv_path.exists():
        parser.error(f"CSV not found: {args.csv_path}")

    with open(args.csv_path, newline="") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        parser.error(f"CSV has no data rows: {args.csv_path}")

    content = generate(rows)
    args.output.write_text(content)
    n_questions = sum(1 for r in rows if (r.get("Question") or "").strip())
    print(f"Wrote {args.output} ({n_questions} questions from {len(rows)} CSV rows)")


if __name__ == "__main__":
    main()
