"""Generate docs/dr-egeria/repo-survey-definition.md from repo's own
STEP_REGISTRY — the reproducible Dr.Egeria document that publishes every
current repo analysis step as a real GovernanceActionProcessStep and chains
them into one runnable Survey Definition.

Analysis-step Egeria registration plan, D1-D3
(docs/analysis-step-egeria-registration-plan.md). Run this whenever
STEP_REGISTRY changes (a step added/removed/re-described) to regenerate the
doc, then execute it against Egeria (see that plan's Verification section)
to keep Discovery's candidate list in sync.

This is the one resource-type-specific piece of the mechanism — everything
it calls (resource_explorer.surveyors.dr_egeria_survey_publisher) is
resource-type-agnostic, so a future database/filesystem equivalent of this
script just needs its own PublishableStep list built from whatever registry
that resource type uses (neither has a STEP_REGISTRY-shaped registry today
— see the plan doc's D1 for why repo went first).
"""
from __future__ import annotations

from pathlib import Path

from resource_explorer.surveyors.dr_egeria_survey_publisher import (
    PublishableStep,
    generate_survey_definition_markdown,
)
from resource_explorer.surveyors.repo_survey_definition_adapter import STEP_REGISTRY

SURVEY_GROUP = "RepoFullSurvey"
SURVEY_DISPLAY_NAME = "Repo Full Survey"
TECHNOLOGY_TYPE = "Git Repository"
SURVEY_DESCRIPTION = (
    "Every current Resource Explorer repo analysis step, chained into one "
    "Survey Definition — regenerated by scripts/generate_repo_survey_definition.py "
    "from repo_survey_definition_adapter.py's STEP_REGISTRY, the single source of "
    "truth for what RE can actually run against a Git repository."
)

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "docs" / "dr-egeria" / "repo-survey-definition.md"


def build_steps() -> list[PublishableStep]:
    return [
        PublishableStep(step_key=key, description=info.description, technology_type=TECHNOLOGY_TYPE)
        for key, info in STEP_REGISTRY.items()
    ]


def main() -> None:
    steps = build_steps()
    markdown = generate_survey_definition_markdown(
        survey_group=SURVEY_GROUP,
        survey_display_name=SURVEY_DISPLAY_NAME,
        technology_type=TECHNOLOGY_TYPE,
        description=SURVEY_DESCRIPTION,
        steps=steps,
    )
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(markdown)
    print(f"Wrote {len(steps)} steps + 1 process + {len(steps)} links to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
