"""Generate all of RE's repo Survey Definition Dr.Egeria docs from repo's own
STEP_REGISTRY — reproducible artifacts that publish repo analysis steps as
real GovernanceActionProcessStep elements and chain them into runnable
Survey Definitions, one per UI surface (survey_kind).

Analysis-step Egeria registration plan, D1-D3
(docs/analysis-step-egeria-registration-plan.md), extended per
docs/discovery-automate-project-context-plan.md Part 1 to generate three
separate Survey Definitions instead of one, each tagged with a survey_kind
Additional Property so Discovery's candidate list doesn't show the
Automate-tier "run everything" bundle (and vice versa):

- **scouting**  — "Repo Coarse Scout": the fast, GitHub-API-only pair
  (repo_health, repo_language) — re-authored here because the original
  live Egeria element was lost to a database reset and never recreated
  (confirmed missing via a live probe before this script was written).
- **discovery** — "Repo Discovery Survey": early-headlights signals from
  data already collected, no new fetch. Currently just
  repo_license_classification (a real, currently-available "should we
  pursue this" signal) — deliberately a minimal, honest interim set;
  grows once Part 2's new Discovery-tier analyses (maturity, security
  policy heuristic, deployment/Docker evidence, etc.) are built.
- **automate_full** — "Repo Full Survey": every current STEP_REGISTRY
  step, chained — the comprehensive bundle for an already-tracked
  resource, not Discovery's launch target. Re-tags the exact same
  qualified_name as before (upsert=true on Create Governance Action
  Process means re-running this in Egeria updates the existing element
  in place, not a duplicate) — only its Additional Properties gain the
  new survey_kind tag.

Run this whenever STEP_REGISTRY changes (a step added/removed/re-described),
then execute the regenerated doc(s) against Egeria to keep Discovery/
Scouting/Automate's candidate lists in sync. IMPORTANT: after executing a
regenerated doc against an *already-linked* process (i.e. every time except
the very first authoring), run
`uv run python scripts/reconcile_survey_definition_links.py` afterward —
Dr.Egeria's "Link First/Next Process Step" commands are not idempotent and
will duplicate or leave stale the step-to-step links, which makes
SurveyDefinitionReader see "branching" and refuse to run the Survey
Definition at all (a real live incident, 2026-08-13 — see that script's and
survey_definition_reconciler.py's docstrings for the full story).

Also emits one "Link Element To Scope" ScopedBy block per Question each
generated Survey Definition answers (docs/survey-question-context-plan.md
D1) — the join is: each step_key's containing analysis_catalog id (via
REPO_ANALYSIS_STEP_MAP) cross-referenced against question_catalog.yaml's
per-question answering.analysis_ids. Run docs/dr-egeria/foundations.md and
docs/dr-egeria/scouting-questions.md (or their generated equivalents)
first — the Question terms these blocks reference by name must already
exist in Egeria before this doc is executed.

This is the one resource-type-specific piece of the mechanism — everything
it calls (resource_explorer.surveyors.dr_egeria_survey_publisher) is
resource-type-agnostic, so a future database/filesystem equivalent of this
script just needs its own PublishableStep list(s) built from whatever
registry that resource type uses (neither has a STEP_REGISTRY-shaped
registry today — see the plan doc's D1 for why repo went first).
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from resource_explorer.surveyors.dr_egeria_survey_publisher import (
    PublishableStep,
    generate_survey_definition_markdown,
)
from resource_explorer.surveyors.question_catalog_reader import get_questions
from resource_explorer.surveyors.repo_survey_definition_adapter import (
    REPO_ANALYSIS_STEP_MAP,
    STEP_REGISTRY,
)

TECHNOLOGY_TYPE = "Git Repository"
DOCS_DIR = Path(__file__).resolve().parent.parent / "docs" / "dr-egeria"


@dataclass(frozen=True)
class SurveyDefSpec:
    survey_kind: str
    survey_group: str
    survey_display_name: str
    description: str
    step_keys: list[str]  # order matters — this is the chain order
    output_filename: str


SPECS = [
    SurveyDefSpec(
        survey_kind="scouting",
        survey_group="RepoCoarseScout",
        survey_display_name="Repo Coarse Scout",
        description=(
            "Fast, GitHub-API-only pass — is this repo active enough to look closer "
            "at? Regenerated by scripts/generate_repo_survey_definition.py. Re-authored "
            "after the original live Egeria element was lost to a database reset."
        ),
        step_keys=["repo_health", "repo_language"],
        output_filename="repo-survey-definition-scouting.md",
    ),
    SurveyDefSpec(
        survey_kind="discovery",
        survey_group="RepoDiscoverySurvey",
        survey_display_name="Repo Discovery Survey",
        description=(
            "Early-headlights signals for deciding whether to pursue this repo further "
            "— from data already collected by Scouting/Profile, zero new fetch. "
            "Grown by Part 2 (docs/discovery-automate-project-context-plan.md) with "
            "maturity/lifecycle-stage and repo-convention signals (security policy, "
            "build automation, deployment/Docker evidence, catalog self-description, "
            "documentation breadth)."
        ),
        step_keys=["repo_license_classification", "repo_maturity", "repo_conventions"],
        output_filename="repo-survey-definition-discovery.md",
    ),
    SurveyDefSpec(
        survey_kind="automate_full",
        survey_group="RepoFullSurvey",
        survey_display_name="Repo Full Survey",
        description=(
            "Every current Resource Explorer repo analysis step, chained into one "
            "Survey Definition — the comprehensive bundle for an already-tracked "
            "repo, not Discovery's launch target. Regenerated by "
            "scripts/generate_repo_survey_definition.py from "
            "repo_survey_definition_adapter.py's STEP_REGISTRY, the single source of "
            "truth for what RE can actually run against a Git repository."
        ),
        step_keys=list(STEP_REGISTRY.keys()),
        output_filename="repo-survey-definition-full.md",
    ),
]


def build_steps(step_keys: list[str]) -> list[PublishableStep]:
    return [
        PublishableStep(
            step_key=key, description=STEP_REGISTRY[key].description, technology_type=TECHNOLOGY_TYPE,
        )
        for key in step_keys
    ]


def _build_step_key_to_questions() -> dict[str, list[str]]:
    """Invert question_catalog.yaml's answering.analysis_ids (analysis_catalog
    id, e.g. "security_scan") through REPO_ANALYSIS_STEP_MAP (analysis id ->
    STEP_REGISTRY step_key(s)) to get step_key -> [question display names] —
    the join docs/survey-question-context-plan.md's D1 depends on. A
    question with no analysis_ids (kind="human"/"gap"/etc.) contributes
    nothing here; that's expected, not every question is answered by a
    survey step at all."""
    mapping: dict[str, list[str]] = {}
    for entry in get_questions(resource_type="repo"):
        for analysis_id in entry["answering"]["analysis_ids"]:
            for step_key in REPO_ANALYSIS_STEP_MAP.get(analysis_id, []):
                mapping.setdefault(step_key, [])
                if entry["question"] not in mapping[step_key]:
                    mapping[step_key].append(entry["question"])
    return mapping


def _answered_questions(step_keys: list[str], step_key_to_questions: dict[str, list[str]]) -> list[str]:
    """Union of questions answered by any step in this Survey Definition,
    order-stable and de-duplicated (a question spanning multiple steps in
    the same spec, e.g. language_file_classification's three-step bundle,
    gets exactly one ScopedBy link, not one per contributing step)."""
    seen: list[str] = []
    for key in step_keys:
        for question in step_key_to_questions.get(key, []):
            if question not in seen:
                seen.append(question)
    return seen


def main() -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    step_key_to_questions = _build_step_key_to_questions()
    for spec in SPECS:
        steps = build_steps(spec.step_keys)
        answers_questions = _answered_questions(spec.step_keys, step_key_to_questions)
        markdown = generate_survey_definition_markdown(
            survey_group=spec.survey_group,
            survey_display_name=spec.survey_display_name,
            technology_type=TECHNOLOGY_TYPE,
            description=spec.description,
            steps=steps,
            survey_kind=spec.survey_kind,
            answers_questions=answers_questions,
        )
        output_path = DOCS_DIR / spec.output_filename
        output_path.write_text(markdown)
        print(
            f"[{spec.survey_kind}] wrote {len(steps)} step(s), "
            f"{len(answers_questions)} question link(s) to {output_path}"
        )


if __name__ == "__main__":
    main()
