"""Dr.Egeria template agent — returns pre-generated markdown command templates."""
from __future__ import annotations

from loguru import logger

from advisor.agents.base import BaseAdvisorAgent


class DrEgeriaTemplateAgent(BaseAdvisorAgent):
    """
    Returns Dr.Egeria markdown command templates for the requested operation.

    Templates are generated by `generate_md_cmd_templates.py` and live at
    {EGERIA_ROOT_PATH}/templates/{basic|advanced}/{family}/{command}.md.
    They can be regenerated at any time with:
        python commands/tech/generate_md_cmd_templates.py
    """

    def system_prompt(self) -> str:
        return (
            "You are an expert on Dr.Egeria, the markdown-based command interface for "
            "the Egeria metadata platform.\n\n"
            "When a user asks for a Dr.Egeria command template or sample:\n"
            "1. Call find_dre_template with the topic (e.g. 'create glossary', 'link term') "
            "and level='basic' unless the user asked for advanced/full details.\n"
            "2. Return the template content verbatim inside a fenced ```markdown block.\n"
            "3. Add a brief explanation (2–3 sentences) covering:\n"
            "   - What the command does.\n"
            "   - Which fields are required (marked 'Input Required: True') vs optional.\n\n"
            "Rules:\n"
            "- Never invent template syntax — only return what find_dre_template returns.\n"
            "- Do NOT add Jupyter notebook usage instructions.\n"
            "- If no template is found, report which families are available and suggest "
            "  the user regenerate templates if the command is new.\n"
        )

    def tools(self) -> list:
        from advisor.agents.tools import find_dre_template
        return [find_dre_template]

    def handle(self, query: str, perspective: str | None = None) -> dict:
        prompt = f"Find and return the Dr.Egeria command sample/example for:\n\n{query}"
        try:
            response = self._run_agent(prompt)
            if "```" in response or "##" in response or "### " in response:
                logger.info("DrEgeriaTemplateAgent: BeeAI returned template content")
                return _make_result(query, response)
        except Exception as exc:
            logger.warning(f"DrEgeriaTemplateAgent BeeAI run failed: {exc}")

        # Fallback: call the tool directly
        logger.info("DrEgeriaTemplateAgent: falling back to direct template lookup")
        return _make_result(query, self._fallback(query, perspective=perspective))

    def _fallback(self, query: str, perspective: str | None = None) -> str:
        from advisor.agents.tools import _find_dre_template_raw
        from advisor.llm_client import get_ollama_client

        level = "advanced" if any(w in query.lower() for w in ("advanced", "full", "expert")) else "basic"
        template_content = _find_dre_template_raw(query, level=level, perspective=perspective)

        if "not found" in template_content.lower() or "no dr.egeria template" in template_content.lower():
            return template_content

        system = (
            "You are an expert on Dr.Egeria markdown commands. "
            "Present the template(s) below cleanly and add a concise explanation."
        )
        user_prompt = (
            f"The user asked: {query}\n\n"
            f"Here is the Dr.Egeria template content:\n\n{template_content}\n\n"
            f"Present this in a fenced ```markdown block, then add 2-3 sentences explaining "
            f"what the command does and which fields are required (Input Required: True). "
            f"Do NOT add Jupyter notebook instructions."
        )
        try:
            return get_ollama_client().generate(user_prompt, system=system, max_tokens=1500)
        except Exception as exc:
            # Return raw template if LLM fails — still useful
            return f"```markdown\n{template_content}\n```"


def _make_result(query: str, response: str) -> dict:
    return {
        "query": query,
        "response": response,
        "query_type": "command",
        "clarification_type": "plan_offer",
        "original_query": query,
        "sources": [],
        "num_sources": 0,
        "retrieval_time": 0.0,
        "generation_time": 0.0,
        "avg_relevance_score": 0.0,
        "context_length": len(response),
    }


_agent: DrEgeriaTemplateAgent | None = None


def get_dre_template_agent() -> DrEgeriaTemplateAgent:
    global _agent
    if _agent is None:
        _agent = DrEgeriaTemplateAgent()
    return _agent
