"""Sub-surveyor: Homepage / external site → ClassificationAnnotation.

Finds the web site that documents a repo — the project's own docs or marketing
site, not the GitHub page. Useful immediately as a navigation shortcut from
Scouting, and useful later as an ingestion target: the docs site usually
explains what a project is *for* in a way the source tree never does, so it is
prime material for the vector store.

Three tiers, in order, and the order matters:

1. GitHub's own `homepage` field, already fetched into project_stats by
   StatsFetcher. Declared by the maintainers, so it is authoritative when set.
   Measured across this deployment's registered repos: 13 of 24 had one.

2. Heuristics over the repo contents, ONLY when tier 1 is empty — which is the
   other 11 of 24, so this is not a rare path. In priority order:
     * pyproject.toml  [project.urls] Homepage / Documentation
     * package.json    "homepage"
     * pom.xml         <url> or <organization><url> (Java — the common case here)
     * Cargo.toml      [package] homepage / documentation
     * setup.cfg       [metadata] url (pre-PEP-621 Python)
     * README          best external link that is not a badge

   Each is a place maintainers deliberately record the project's site, so a hit
   is a statement of intent rather than an inference. The README pass is the
   weakest and is treated as such: it is last, it skips badge/shield images and
   link targets, skips known vendor/attribution hosts, ignores links back to the
   repo's own host, and prefers a hostname echoing the org/repo name over mere
   document order.

3. The repo URL itself, when nothing else is found. For a small project there
   frequently is no separate site — the GitHub page *is* the landing page and
   the README is the documentation. Marked is_external_site=false and given low
   confidence so a consumer wanting a genuinely off-GitHub site to ingest can
   filter it out, while the Scouting link stays actionable for every repo.

Confidence is reported per tier rather than flattened, so a consumer can tell a
maintainer-declared URL from one scraped out of a README.

Runs as a survey step rather than at publish time because tier 2 needs the repo
contents. It declares requires_resources={"zipball_root": ...}, so
resolve_resources shares one download with the other zipball steps and this
costs no extra fetch. It also means the answer refreshes on every survey instead
of being frozen at registration.

A found URL is persisted via registry.update_project_homepage() (see that
method for why it writes projects.homepage_url rather than project_stats) and
published to Egeria by EgeriaPublisher as an ExternalReference linked to the
repo's SourceControlLibrary.
"""
from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from urllib.parse import urlparse

from resource_explorer.registry import Project, ProjectRegistry
from resource_explorer.surveyors.base_surveyor import BaseSurveyor
from resource_explorer.step_outcome import StepOutcome, no_signal
from resource_explorer.surveyors.survey_report import Annotation, ClassificationAnnotation

log = logging.getLogger(__name__)

STEP = "Homepage"

# Hosts that are never "the project's external site" — they are where the code
# already lives, or a badge/CI service. A repo whose declared homepage is its
# own GitHub page tells us nothing new.
_CODE_HOSTS = {"github.com", "www.github.com", "gitlab.com", "bitbucket.org"}
# Tooling/vendor sites that appear in READMEs as attribution ("generated by
# ...", "powered by ...") and are never the project's own site. Found the hard
# way: unitycatalog-python's README yielded stainlessapi.com, its SDK generator.
_VENDOR_HOSTS = {
    "stainlessapi.com", "www.stainlessapi.com", "speakeasyapi.dev",
    "www.speakeasyapi.dev", "openapi-generator.tech", "swagger.io",
    "readthedocs.org", "readthedocs.com", "netlify.com", "vercel.com",
    "opensource.org", "creativecommons.org", "contributor-covenant.org",
    "semver.org", "keepachangelog.com", "conventionalcommits.org",
}

_BADGE_HOSTS = {
    "img.shields.io", "shields.io", "badge.fury.io", "travis-ci.org",
    "travis-ci.com", "codecov.io", "coveralls.io", "circleci.com",
    "app.codacy.com", "sonarcloud.io", "badgen.net", "anaconda.org",
}

# Markdown inline link/image: captures ![alt](url) vs [text](url) via group 1.
_MD_LINK = re.compile(r"(!?)\[[^\]]*\]\(\s*(<?)(https?://[^\s)>]+)\2\s*[^)]*\)")


def _host(url: str) -> str:
    try:
        return (urlparse(url).hostname or "").lower()
    except Exception:
        return ""


def _is_plausible_site(url: str, repo_host: str = "") -> bool:
    """Reject the things that are technically links but never the project site."""
    h = _host(url)
    if not h or h in _BADGE_HOSTS or h in _CODE_HOSTS or h in _VENDOR_HOSTS:
        return False
    if repo_host and h == repo_host:
        return False
    return True


class HomepageSurveyor(BaseSurveyor):
    """Derives the project's external website. See module docstring for tiers."""

    def __init__(
        self, project: Project, registry: ProjectRegistry, local_path: str | None = None,
        surveyed_at: str | None = None,
    ) -> None:
        super().__init__(project, registry)
        self._local_path = local_path
        self._surveyed_at = surveyed_at

    @property
    def step_name(self) -> str:
        return STEP

    # ── tier 1 ──────────────────────────────────────────────────────────────
    def _from_github(self) -> str:
        try:
            stats = self.registry.get_latest_project_stats(self.project.slug) or {}
        except Exception:
            return ""
        return (stats.get("homepage") or "").strip()

    # ── tier 2 ──────────────────────────────────────────────────────────────
    def _from_pyproject(self, root: Path) -> str:
        f = root / "pyproject.toml"
        if not f.is_file():
            return ""
        try:
            import tomllib

            urls = (tomllib.loads(f.read_text(encoding="utf-8", errors="ignore"))
                    .get("project", {}).get("urls", {}) or {})
        except Exception:
            return ""
        # Case-insensitive: PEP 621 does not fix the casing of these keys.
        lowered = {str(k).lower(): str(v) for k, v in urls.items()}
        for key in ("homepage", "documentation", "docs"):
            v = lowered.get(key, "").strip()
            if v and _is_plausible_site(v):
                return v
        return ""

    def _from_package_json(self, root: Path) -> str:
        f = root / "package.json"
        if not f.is_file():
            return ""
        try:
            hp = json.loads(f.read_text(encoding="utf-8", errors="ignore")).get("homepage")
        except Exception:
            return ""
        hp = (hp or "").strip() if isinstance(hp, str) else ""
        return hp if hp and _is_plausible_site(hp) else ""

    def _from_maven(self, root: Path) -> str:
        """Maven POM <url> / <organization><url>. Worth having: this deployment
        is Egeria-centric and most of those repos are Java, where pyproject and
        package.json never appear."""
        f = root / "pom.xml"
        if not f.is_file():
            return ""
        try:
            import xml.etree.ElementTree as ET

            root_el = ET.fromstring(f.read_text(encoding="utf-8", errors="ignore"))
        except Exception:
            return ""
        # POMs are namespaced; match on the local tag name instead of guessing
        # which Maven schema version this file uses.
        def _local(el):
            return el.tag.rsplit("}", 1)[-1]

        for el in root_el:
            if _local(el) == "url" and (el.text or "").strip():
                v = el.text.strip()
                if _is_plausible_site(v):
                    return v
        for el in root_el.iter():
            if _local(el) == "organization":
                for child in el:
                    if _local(child) == "url" and (child.text or "").strip():
                        v = child.text.strip()
                        if _is_plausible_site(v):
                            return v
        return ""

    def _from_cargo(self, root: Path) -> str:
        f = root / "Cargo.toml"
        if not f.is_file():
            return ""
        try:
            import tomllib

            pkg = tomllib.loads(f.read_text(encoding="utf-8", errors="ignore")).get("package", {}) or {}
        except Exception:
            return ""
        for key in ("homepage", "documentation"):
            v = str(pkg.get(key) or "").strip()
            if v and _is_plausible_site(v):
                return v
        return ""

    def _from_setup_cfg(self, root: Path) -> str:
        """Pre-PEP-621 Python packaging, still common in older repos."""
        f = root / "setup.cfg"
        if not f.is_file():
            return ""
        try:
            import configparser

            cp = configparser.ConfigParser()
            cp.read_string(f.read_text(encoding="utf-8", errors="ignore"))
            v = (cp.get("metadata", "url", fallback="") or "").strip()
        except Exception:
            return ""
        return v if v and _is_plausible_site(v) else ""

    def _from_readme(self, root: Path) -> str:
        for name in ("README.md", "README.rst", "readme.md", "README"):
            f = root / name
            if not f.is_file():
                continue
            try:
                text = f.read_text(encoding="utf-8", errors="ignore")
            except Exception:
                continue
            repo_host = _host(self.project.github_url)
            candidates = []
            for is_image, _br, url in _MD_LINK.findall(text):
                if is_image:          # ![...](...) is a badge/screenshot, not a site
                    continue
                url = url.rstrip(".,;")
                if _is_plausible_site(url, repo_host):
                    candidates.append(url)
            if not candidates:
                continue
            # Prefer a host that echoes the org or repo name. "First plausible
            # link" alone is too loose — it picked an SDK vendor's marketing site
            # over the actual project. A hostname containing the project's own
            # name is a much stronger signal than document order.
            for token in self._name_tokens():
                for url in candidates:
                    if token and token in _host(url).replace("-", "").replace(".", ""):
                        return url
            return candidates[0]
        return ""

    def _name_tokens(self) -> list[str]:
        """org and repo names from the GitHub URL, normalised for host matching."""
        parts = [p for p in urlparse(self.project.github_url).path.split("/") if p]
        out = []
        for p in parts[:2]:
            t = p.removesuffix(".git").lower().replace("-", "").replace("_", "")
            if len(t) >= 4:      # "ol", "re" etc. would match almost anything
                out.append(t)
        return list(reversed(out))   # repo name is the stronger signal, try it first

    def run(self) -> list[Annotation]:
        homepage, source, confidence = self._from_github(), "github_homepage", 100

        if not homepage and self._local_path:
            root = Path(self._local_path)
            # Manifests first, README last: a manifest URL is something a
            # maintainer wrote down on purpose, a README link is something we
            # inferred from prose.
            for finder, label, conf in (
                (self._from_pyproject, "pyproject_urls", 90),
                (self._from_package_json, "package_json", 90),
                (self._from_maven, "maven_pom", 90),
                (self._from_cargo, "cargo_toml", 90),
                (self._from_setup_cfg, "setup_cfg", 85),
                (self._from_readme, "readme_link", 60),
            ):
                try:
                    found = finder(root)
                except Exception as exc:      # a malformed file must not end the survey
                    log.debug("HomepageSurveyor %s failed for %s: %s", label, self.project.slug, exc)
                    continue
                if found:
                    homepage, source, confidence = found, label, conf
                    break

        # Tier 3 — the repo itself. For a small project there often is no separate
        # site and the GitHub page *is* the landing page: the README is the docs,
        # and it is where you would send someone. Recording that is more useful
        # than recording nothing, and it keeps the Scouting link always
        # actionable. Distinguished from a real external site by its low
        # confidence and its derivation_source, so a consumer that specifically
        # wants an off-GitHub site to ingest can filter it out — which is why
        # _is_plausible_site still rejects code hosts for tiers 1 and 2. This is
        # a deliberate last-resort default, not a discovery.
        fell_back_to_repo = False
        if not homepage and self.project.github_url:
            homepage = self.project.github_url.removesuffix(".git")
            source, confidence, fell_back_to_repo = "repo_url", 30, True

        if not homepage:
            return [
                ClassificationAnnotation(
                    summary="No external site found",
                    analysis_step=STEP,
                    confidence=100,
                    explanation=(
                        "GitHub declares no homepage, nothing was found in pyproject.toml, "
                        "package.json or the README, and the project has no repo URL to fall "
                        "back on. A real answer, not a failure."
                    ),
                    candidate_classifications=[],
                    # This step's explanation already ends "A real answer, not
                    # a failure", and it has earned that: GitHub's declared
                    # homepage, pyproject, package.json, the README and the
                    # repo URL were all checked. Those sources ARE the
                    # known-positive, which is what makes this the rare zero
                    # that can be claimed as provable rather than merely
                    # observed.
                    json_properties=no_signal(
                        "no homepage in any declared source, and no repo URL to fall back on",
                        known_positive=True).as_row(),
                )
            ]

        try:
            self.registry.update_project_homepage(self.project.slug, homepage)
        except Exception as exc:
            log.warning("Could not persist homepage for %s: %s", self.project.slug, exc)

        label = "Project page (repo)" if fell_back_to_repo else "External site"
        return [
            ClassificationAnnotation(
                summary=f"{label}: {homepage}",
                analysis_step=STEP,
                confidence=confidence,
                json_properties=(
                    # Falling back to the repo URL is not the same as finding a
                    # site — the step already says so with confidence 30, and
                    # `partial` is the matching label: something produced,
                    # knowingly not the thing asked for.
                    StepOutcome("partial", cause="fell back to the repo URL",
                                detail={"source": source})
                    if fell_back_to_repo else
                    StepOutcome("recovered", detail={"source": source})
                ).as_row(),
                explanation=(
                    f"Derived from {source}. Tier 1 is GitHub's declared homepage; the "
                    f"pyproject/package.json/README tiers run only when that is empty; the "
                    f"repo URL itself is the last resort, for small projects whose GitHub "
                    f"page really is their landing page. Confidence reflects the tier — a "
                    f"maintainer-declared URL, a README link and a repo-URL fallback are "
                    f"three different strengths of claim."
                ),
                candidate_classifications=[homepage],
                additional_properties={
                    "homepage_url": homepage,
                    "derivation_source": source,
                    "is_external_site": str(not fell_back_to_repo).lower(),
                },
            )
        ]
