"""Sub-surveyor: Website Ingestion → ResourceMeasureAnnotation.

Ingests a project's documentation site into pgvector so Chat and Understanding
can answer from it. The docs site explains what a project is *for* in a way the
source tree never does, which is why it is worth having alongside repo ingestion.

Everything hard about this is deciding *what* to ingest; see
`resource_explorer/ingestion/site_discovery.py`, which holds that logic so it can
be tested without network. Three findings from running it against real projects
shape this step:

**The site belongs to the project, not the repo.** Four registered repos here
(egeria_git, egeria_docs, egeria_python_git, trellis) all declare
https://egeria-project.org and all sit in the same `egeria` group. So the
collection is keyed on the site's host, not the repo slug — ingested once, and
listed by every repo pointing at it, so the query router finds it whichever repo
the user is looking at. A per-repo collection would embed one site four times and
still leave each repo able to search only its own copy.

**Some sites must not be ingested at all.** egeria-project.org is generated by
the egeria-docs repo, which Resource Explorer already registers and ingests. The
rendered HTML would duplicate content we already hold in a better form — source
markdown rather than HTML boilerplate. This step detects that (a site-generator
marker in the repo's own file inventory) and skips, which is the one outcome most
easily mistaken for a bug: the ingest would otherwise succeed and look productive.

**A sitemap is not a page list.** openlineage.io's sitemap has 2,460 URLs, but
2,398 of them are the same ~220 docs pages repeated across ten releases.
Ingesting all of them embeds ten near-identical copies of every passage, so a
query matches a dozen versions with no basis for choosing between them —
retrieval gets worse while the chunk count looks impressive. Collapsed to 447.

Not a crawler: it reads the site's own sitemap, and falls back to the single page
when there isn't one rather than following links. Bounded by max_pages.
"""
from __future__ import annotations

import logging
from datetime import datetime

from resource_explorer.registry import Project, ProjectRegistry
from resource_explorer.surveyors.base_surveyor import BaseSurveyor
from resource_explorer.surveyors.survey_report import Annotation, ResourceMeasureAnnotation

log = logging.getLogger(__name__)

STEP = "WebsiteIngestion"

_MAX_PAGES = 400
_TIMEOUT = 25


class WebsiteIngestionSurveyor(BaseSurveyor):
    """Ingests the project's documentation site into a host-keyed pgvector
    collection. See module docstring for why each decision is what it is."""

    def __init__(
        self, project: Project, registry: ProjectRegistry, surveyed_at: str | None = None,
        max_pages: int = _MAX_PAGES,
    ) -> None:
        super().__init__(project, registry)
        self._surveyed_at = surveyed_at or datetime.utcnow().isoformat()
        self._max_pages = max_pages

    @property
    def step_name(self) -> str:
        return STEP

    # ── helpers ─────────────────────────────────────────────────────────────
    @staticmethod
    def _fetch(url: str) -> str | None:
        import urllib.request

        try:
            req = urllib.request.Request(url, headers={"User-Agent": "resource-explorer/1.0"})
            with urllib.request.urlopen(req, timeout=_TIMEOUT) as resp:
                return resp.read().decode("utf-8", errors="ignore")
        except Exception as exc:
            log.debug("website fetch failed for %s: %s", url, exc)
            return None

    def _note(self, summary: str, explanation: str, props: dict, confidence: int = 100
              ) -> list[Annotation]:
        return [ResourceMeasureAnnotation(
            summary=summary, analysis_step=STEP, confidence=confidence,
            explanation=explanation,
            resource_properties={**props, "surveyed_at": self._surveyed_at},
        )]

    # ── run ─────────────────────────────────────────────────────────────────
    def run(self) -> list[Annotation]:
        from resource_explorer.ingestion.site_discovery import (
            discover_pages,
            repo_publishes_site,
            site_collection_name,
        )

        url = (self.project.homepage_url or "").strip()
        if not url:
            return self._note(
                "No website to ingest", "This project has no external site recorded. Run "
                "repo_homepage first — it derives one from GitHub, the packaging manifests "
                "or the README.", {"ingested": False, "reason": "no_homepage"})

        # Skip a site whose source we already ingest as a repo (see docstring).
        try:
            marker = repo_publishes_site(self.registry.get_file_inventory(self.project.slug))
        except Exception:
            marker = ""
        if marker:
            return self._note(
                f"Skipped — this repo publishes {url}",
                f"Found {marker}, so this repo is the source of its own website. The content "
                "is already ingested as repository source, in a better form than the rendered "
                "HTML would be. Ingesting it again would duplicate the same material and "
                "split retrieval across two copies of it.",
                {"ingested": False, "reason": "self_published", "marker": marker, "url": url})

        try:
            pages, how = discover_pages(url, self._fetch, max_pages=self._max_pages)
        except Exception as exc:
            log.warning("site discovery failed for %s: %s", self.project.slug, exc)
            return self._note("Website discovery failed", f"Could not work out which pages of "
                              f"{url} to ingest: {exc}", {"ingested": False, "error": str(exc)},
                              confidence=0)

        collection = site_collection_name(url)
        chunks_added, fetched, failed = 0, 0, 0
        try:
            from resource_explorer.configdata.collection_config import COLLECTION_TYPES
            from resource_explorer.vector_store_pg import MultiCollectionStore

            ctype = COLLECTION_TYPES.get("web_docs")
            if ctype is None:
                return self._note("web_docs collection type is not configured",
                                  "Cannot ingest a website without its chunking configuration.",
                                  {"ingested": False, "reason": "no_collection_type"}, confidence=0)

            store = MultiCollectionStore()
            texts, metas = [], []
            for page in pages:
                html = self._fetch(page)
                if not html:
                    failed += 1
                    continue
                fetched += 1
                text = _extract_text(html)
                if not text:
                    continue
                for i, chunk in enumerate(_chunk(text, ctype)):
                    texts.append(chunk)
                    metas.append({"file_path": page, "source": "website",
                                  "chunk_index": i, "url": page})

            if texts:
                # MultiCollectionStore.insert() embeds and returns the row count —
                # there is no separate insert_with_embeddings on this class.
                chunks_added = store.insert(collection, texts, metas)
                # Register on THIS repo so the query router searches it. Other
                # repos sharing the site register it on their own runs — the
                # collection itself is shared, keyed on the host.
                cols = list(self.project.collections or [])
                if collection not in cols:
                    cols.append(collection)
                    self.registry.update_indexed_at(self.project.slug, cols)
        except Exception as exc:
            log.warning("website ingestion failed for %s: %s", self.project.slug, exc)
            return self._note("Website ingestion failed", f"Discovered {len(pages)} page(s) via "
                              f"{how} but could not embed them: {exc}",
                              {"ingested": False, "error": str(exc), "pages_found": len(pages)},
                              confidence=0)

        return self._note(
            f"{chunks_added} chunk(s) from {fetched} page(s) of {url}",
            f"Discovered {len(pages)} page(s) via {how}, fetched {fetched}"
            + (f" ({failed} unreachable)" if failed else "")
            + f", embedded into {collection}. The collection is keyed on the site's host rather "
            "than this repo, so every repo sharing this website searches the same copy.",
            {"ingested": True, "url": url, "collection": collection,
             "pages_found": len(pages), "pages_fetched": fetched, "pages_failed": failed,
             "chunks": chunks_added, "discovery": how},
            confidence=100 if chunks_added else 50)


def _extract_text(html: str) -> str:
    """Strip a page to its readable text.

    Deliberately not Docling here: these are ordinary HTML pages and Docling's
    converter added a heavyweight dependency on the hot path for no gain over
    tag-stripping — measured while building this, it extracted almost nothing
    from the two sites tried. Script/style/nav/header/footer go first so site
    chrome does not become chunks that match every query.
    """
    import html as _html
    import re

    body = re.sub(r"(?s)<(script|style|nav|header|footer|aside)[^>]*>.*?</\1>", " ", html)
    text = _html.unescape(re.sub(r"<[^>]+>", " ", body))
    return re.sub(r"\s+", " ", text).strip()


def _chunk(text: str, ctype) -> list[str]:
    """Split using the web_docs collection type's own chunk size, so website
    content is chunked the same way every other web content in this system is."""
    size = getattr(ctype, "chunk_size", 1000) or 1000
    overlap = getattr(ctype, "chunk_overlap", 100) or 0
    step = max(1, size - overlap)
    return [text[i:i + size] for i in range(0, len(text), step) if text[i:i + size].strip()]
