"""Sub-surveyor: Website Ingestion → ResourceMeasureAnnotation.

Ingests a project's documentation site into pgvector so Chat and Understanding
can answer from it. The docs site explains what a project is *for* in a way the
source tree never does, which is why it is worth having alongside repo ingestion.

Everything hard about this is deciding *what* to ingest; see
`resource_explorer/ingestion/site_discovery.py`, which holds that logic so it can
be tested without network. Three findings from running it against real projects
shape this step:

**The site belongs to the project, not the repo.** Four registered repos here
(egeria_git, egeria_docs, egeria_python_git, trellis) all declare
https://egeria-project.org and all sit in the same `egeria` group. So the
collection is keyed on the site's host, not the repo slug — ingested once, and
listed by every repo pointing at it, so the query router finds it whichever repo
the user is looking at. A per-repo collection would embed one site four times and
still leave each repo able to search only its own copy.

**Some sites must not be ingested at all.** egeria-project.org is generated by
the egeria-docs repo, which Resource Explorer already registers and ingests. The
rendered HTML would duplicate content we already hold in a better form — source
markdown rather than HTML boilerplate. This step detects that (a site-generator
marker in the repo's own file inventory) and skips, which is the one outcome most
easily mistaken for a bug: the ingest would otherwise succeed and look productive.

**A sitemap is not a page list.** openlineage.io's sitemap has 2,460 URLs, but
2,398 of them are the same ~220 docs pages repeated across ten releases.
Ingesting all of them embeds ten near-identical copies of every passage, so a
query matches a dozen versions with no basis for choosing between them —
retrieval gets worse while the chunk count looks impressive. Collapsed to 456.

Not a crawler: it reads the site's own sitemap, and falls back to the single page
when there isn't one rather than following links. Bounded by max_pages.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime

from resource_explorer.registry import Project, ProjectRegistry
from resource_explorer.step_outcome import (
    PARTIAL,
    RECOVERED,
    UNVERIFIED,
    StepOutcome,
    no_signal,
)
from resource_explorer.surveyors.base_surveyor import BaseSurveyor
from resource_explorer.surveyors.survey_report import Annotation, ResourceMeasureAnnotation

log = logging.getLogger(__name__)

STEP = "WebsiteIngestion"

_MAX_PAGES = 400
_TIMEOUT = 25


class WebsiteIngestionSurveyor(BaseSurveyor):
    """Ingests the project's documentation site into a host-keyed pgvector
    collection. See module docstring for why each decision is what it is."""

    def __init__(
        self, project: Project, registry: ProjectRegistry, surveyed_at: str | None = None,
        max_pages: int = _MAX_PAGES,
    ) -> None:
        super().__init__(project, registry)
        self._surveyed_at = surveyed_at or datetime.utcnow().isoformat()
        self._max_pages = max_pages

    @property
    def step_name(self) -> str:
        return STEP

    # ── helpers ─────────────────────────────────────────────────────────────
    @staticmethod
    def _fetch(url: str) -> str | None:
        import urllib.request

        try:
            req = urllib.request.Request(url, headers={"User-Agent": "resource-explorer/1.0"})
            with urllib.request.urlopen(req, timeout=_TIMEOUT) as resp:
                return resp.read().decode("utf-8", errors="ignore")
        except Exception as exc:
            log.debug("website fetch failed for %s: %s", url, exc)
            return None

    def _note(self, summary: str, explanation: str, props: dict, confidence: int = 100,
              outcome: "StepOutcome | None" = None) -> list[Annotation]:
        """Build this step's single annotation, and persist the same numbers as a
        metric so the Analysis card has something to render.

        Every terminal path in run() returns through here, including the skips and
        failures — deliberately, so a repo that publishes its own site shows
        "0 chunks, reason: self_published" on its card rather than an empty panel
        indistinguishable from "never run". The reason string is what makes that
        outcome legible as a decision rather than a fault.
        """
        # A fixed allowlist, so a key added upstream and not added here is
        # dropped SILENTLY — which is exactly what happened to `ingested_by`
        # when the dedup skip was written, and to `operationCount` in
        # arch_recovery/persist.py earlier the same day. The list stays explicit
        # (an unbounded passthrough would let anything into the record) but the
        # hazard is worth naming at the point it bites.
        detail = {k: v for k, v in props.items()
                  if k in ("url", "collection", "reason", "marker", "discovery",
                           "pages_found", "pages_failed", "ingested", "error",
                           "ingested_by", "ingested_at", "owner_repo")}
        if outcome is not None:
            # The shared vocabulary (resource_explorer/step_outcome.py) alongside
            # this step's own `reason`. Both are kept: the outcome is queryable
            # across every step, the cause is local knowledge, and Egeria's guard
            # is a flat token so they could not be one field even if we wanted.
            detail.update(outcome.as_row())
        try:
            self.registry.upsert_metric(
                self.project.slug, "website_ingestion",
                {"chunks": int(props.get("chunks", 0) or 0),
                 "pages_fetched": int(props.get("pages_fetched", 0) or 0)},
                detail=detail,
                surveyed_at=self._surveyed_at,
            )
        except Exception as exc:
            log.warning("Could not persist website ingestion snapshot for %s: %s",
                        self.project.slug, exc)

        return [ResourceMeasureAnnotation(
            summary=summary, analysis_step=STEP, confidence=confidence,
            explanation=explanation,
            resource_properties={**props, "surveyed_at": self._surveyed_at},
        )]

    # ── run ─────────────────────────────────────────────────────────────────
    def run(self) -> list[Annotation]:
        from resource_explorer.ingestion.site_discovery import (
            discover_pages,
            host_relates_to_project,
    is_code_host,
    is_non_doc_host,
            repo_publishes_site,
            site_collection_name,
        )

        url = (self.project.homepage_url or "").strip()
        if not url:
            return self._note(
                "No website to ingest", "This project has no external site recorded. Run "
                "repo_homepage first — it derives one from GitHub, the packaging manifests "
                "or the README.", {"ingested": False, "reason": "no_homepage"},
                outcome=StepOutcome(UNVERIFIED, cause="no_homepage",
                                    detail={"needs": "repo_homepage"}))

        # A homepage pointing back at the forge is not a documentation site.
        # repo_homepage falls back to manifest/README URLs when GitHub declares
        # no homepage, and those are sometimes the repo's own URL.
        if is_code_host(url):
            return self._note(
                "No documentation site — homepage is the code host",
                f"{url} is the repository's own forge page, not a documentation site. "
                "Ingesting it would embed the forge's navigation and file listings as if "
                "they were documentation. Nothing to do until this project publishes docs "
                "somewhere else.",
                {"ingested": False, "reason": "code_host", "url": url},
                # Provable: the URL was resolved and positively identified as a
                # forge page, so the zero is the answer rather than a failure to
                # look.
                outcome=no_signal("code_host", known_positive=True, url=url))

        # A badge, a registry or a dataset hub is not documentation. Measured
        # 2026-08-25: a pilot fed this step three deliberately-bad homepages and
        # it ingested all three, because `repo_homepage` falls back to README
        # links and a README's first link is very often a badge.
        if is_non_doc_host(url):
            return self._note(
                "No documentation site — homepage is not a documentation host",
                f"{url} is a badge, registry or dataset host, not this project's "
                f"documentation. `repo_homepage` falls back to manifest and README "
                f"URLs when GitHub declares no homepage, and those are frequently "
                f"badges. Ingesting it would embed an image page or a package "
                f"listing as if it were documentation.",
                {"ingested": False, "reason": "non_doc_host", "url": url},
                outcome=no_signal("non_doc_host", known_positive=True, url=url))

        # Skip a site whose source we already ingest as a repo (see docstring).
        try:
            marker = repo_publishes_site(self.registry.get_file_inventory(self.project.slug))
        except Exception:
            marker = ""
        if marker:
            return self._note(
                f"Skipped — this repo publishes {url}",
                f"Found {marker}, so this repo is the source of its own website. The content "
                "is already ingested as repository source, in a better form than the rendered "
                "HTML would be. Ingesting it again would duplicate the same material and "
                "split retrieval across two copies of it.",
                {"ingested": False, "reason": "self_published", "marker": marker, "url": url},
                # The marker in the repo's own file inventory is the
                # known-positive: something was found, and it is what rules the
                # ingest out.
                outcome=no_signal("self_published", known_positive=True, marker=marker))

        # Ordering matters and an existing test caught it: this runs AFTER the
        # self-published check, never before. A marker in the repo's own file
        # inventory is DIRECT evidence that this project publishes this site,
        # and it outranks a name heuristic — `odpi/egeria` builds
        # `egeria-project.org`, and a project whose site is named nothing like
        # its repo would otherwise be refused as somebody else's while we hold
        # proof that it is theirs.
        #
        # A real documentation site belonging to SOMEBODY ELSE is the harder
        # case, and the one that did real damage in the pilot: `docling-nlp`'s
        # homepage resolved to `docs.astral.sh/uv/`, and ingesting it pulled
        # 3096 chunks of the uv package manager's documentation into a
        # collection attributed to docling. No host list catches that — the host
        # is a perfectly good documentation site, just not this project's.
        owner_repo = "/".join(
            (getattr(self.project, "github_url", "") or "").rstrip("/")
            .removesuffix(".git").split("/")[-2:])
        if owner_repo and not host_relates_to_project(url, owner_repo):
            return self._note(
                "Homepage does not appear to belong to this project",
                f"{url} shares no name with {owner_repo}, so it is probably another "
                f"project's site picked up from a README link rather than this "
                f"project's documentation. Refused rather than skipped silently: if "
                f"this project really does publish there, that is worth correcting "
                f"and this message is where to start.",
                {"ingested": False, "reason": "unrelated_host", "url": url,
                 "owner_repo": owner_repo},
                outcome=no_signal("unrelated_host", known_positive=True, url=url))


        try:
            pages, how = discover_pages(url, self._fetch, max_pages=self._max_pages)
        except Exception as exc:
            log.warning("site discovery failed for %s: %s", self.project.slug, exc)
            return self._note("Website discovery failed", f"Could not work out which pages of "
                              f"{url} to ingest: {exc}", {"ingested": False, "error": str(exc)},
                              confidence=0,
                              outcome=StepOutcome(UNVERIFIED, cause="discovery_failed",
                                                  detail={"error": str(exc)[:200]}))

        collection = site_collection_name(url)

        # Somebody else may already have done this. The collection is keyed on
        # the site's host precisely so sibling repos share one — sharing the
        # destination without sharing the work is what made egeria-project.org
        # cost three full ingests in one batch.
        owner, when = _already_ingested(self.registry, collection, self.project.slug)
        if owner:
            # Still register it HERE, which is the part that matters: the query
            # router searches a repo's own collection list, so skipping the
            # fetch must not also skip the wiring, or this repo would be unable
            # to search a site it points at.
            cols = list(self.project.collections or [])
            if collection not in cols:
                cols.append(collection)
                self.registry.update_indexed_at(self.project.slug, cols)
            return self._note(
                f"Already ingested — {collection} came from {owner}",
                f"{url} was ingested as {collection} by '{owner}' at {when}, within the "
                f"{SITE_FRESHNESS_HOURS}h freshness window. The collection is keyed on the "
                f"site's host so sibling repos share one copy; it is registered on this repo "
                f"so its questions search it, and re-fetching would embed the same pages "
                f"again and split retrieval across duplicates.",
                {"ingested": False, "reason": "already_ingested", "url": url,
                 "collection": collection, "ingested_by": owner, "ingested_at": when},
                outcome=no_signal("already_ingested", known_positive=True,
                                  collection=collection, by=owner))
        chunks_added, fetched, failed = 0, 0, 0
        try:
            from resource_explorer.configdata.collection_config import COLLECTION_TYPES
            from resource_explorer.vector_store_pg import MultiCollectionStore

            ctype = COLLECTION_TYPES.get("web_docs")
            if ctype is None:
                return self._note("web_docs collection type is not configured",
                                  "Cannot ingest a website without its chunking configuration.",
                                  {"ingested": False, "reason": "no_collection_type"}, confidence=0,
                                  outcome=StepOutcome(UNVERIFIED, cause="no_collection_type"))

            store = MultiCollectionStore()
            texts, metas = [], []
            for page in pages:
                html = self._fetch(page)
                if not html:
                    failed += 1
                    continue
                fetched += 1
                text = _extract_text(html)
                if not text:
                    continue
                for i, chunk in enumerate(_chunk(text, ctype)):
                    texts.append(chunk)
                    metas.append({"file_path": page, "source": "website",
                                  "chunk_index": i, "url": page})

            if texts:
                # MultiCollectionStore.insert() embeds and returns the row count —
                # there is no separate insert_with_embeddings on this class.
                chunks_added = store.insert(collection, texts, metas)
                # Register on THIS repo so the query router searches it. Other
                # repos sharing the site register it on their own runs — the
                # collection itself is shared, keyed on the host.
                cols = list(self.project.collections or [])
                if collection not in cols:
                    cols.append(collection)
                    self.registry.update_indexed_at(self.project.slug, cols)
        except Exception as exc:
            log.warning("website ingestion failed for %s: %s", self.project.slug, exc)
            return self._note("Website ingestion failed", f"Discovered {len(pages)} page(s) via "
                              f"{how} but could not embed them: {exc}",
                              {"ingested": False, "error": str(exc), "pages_found": len(pages)},
                              confidence=0,
                              outcome=StepOutcome(UNVERIFIED, cause="ingest_failed",
                                                  detail={"error": str(exc)[:200],
                                                          "pages_found": len(pages)}))

        # What was actually achieved, in the shared vocabulary:
        #   chunks + nothing unreachable  -> recovered
        #   chunks + some pages missing   -> partial (knowingly incomplete)
        #   no chunks, pages were fetched -> the site was reached and yielded
        #       nothing; the fetch itself is the known-positive, so this is a
        #       provable no_signal rather than a failure to look
        #   no chunks, nothing fetched    -> unverified; the site was never read
        if chunks_added and failed:
            outcome = StepOutcome(PARTIAL, cause="pages_unreachable",
                                  detail={"fetched": fetched, "failed": failed})
        elif chunks_added:
            outcome = StepOutcome(RECOVERED, cause="",
                                  detail={"chunks": chunks_added, "pages": fetched})
        elif fetched:
            # Reached the site and it yielded no text — the fetch itself is the
            # known-positive, so this is a provable no_signal.
            outcome = no_signal("no_extractable_text", known_positive=True,
                                fetched=fetched, failed=failed)
        else:
            # NOTHING was fetched. Distinct from the branch above, and the two
            # were one `else` until 2026-08-25 even though the comment beside it
            # already distinguished them. `milvus` is the case: 400 pages found
            # via sitemap, 400 fetches failed (milvus.io 302-loops for a
            # non-browser client), 685 seconds spent, and it reported cause
            # `no_extractable_text` about text it never had the chance to read.
            outcome = StepOutcome(UNVERIFIED, cause="no_pages_fetched",
                                  detail={"found": len(pages), "failed": failed})

        return self._note(
            f"{chunks_added} chunk(s) from {fetched} page(s) of {url}",
            f"Discovered {len(pages)} page(s) via {how}, fetched {fetched}"
            + (f" ({failed} unreachable)" if failed else "")
            + f", embedded into {collection}. The collection is keyed on the site's host rather "
            "than this repo, so every repo sharing this website searches the same copy.",
            # `ingested` reflects what actually landed. It was hardcoded True
            # on this path regardless of `chunks_added`, so `milvus` reported
            # `ingested: True` after 400 failed fetches — and downstream code
            # reads this flag rather than the outcome beside it, which had the
            # answer right. A redundant boolean that can disagree with the
            # authoritative field is worse than no boolean.
            {"ingested": bool(chunks_added), "url": url, "collection": collection,
             "pages_found": len(pages), "pages_fetched": fetched, "pages_failed": failed,
             "chunks": chunks_added, "discovery": how},
            confidence=100 if chunks_added else 50,
            outcome=outcome)


#: How long an ingested site is treated as current. A documentation site does
#: not change hourly, and the cost of being a day stale is far below the cost of
#: re-fetching it for every sibling repo. A daily scheduled survey therefore
#: re-ingests once a day; a batch across 60 repos ingests each site once.
SITE_FRESHNESS_HOURS = 24


def _already_ingested(registry, collection: str, this_slug: str):
    """`(slug, when)` if `collection` was ingested recently with content in it,
    by ANY repo including this one. `(None, None)` otherwise.

    `site_collection_name`'s own docstring says a site should be "ingested once
    and every repo pointing at it" shares the copy — the naming did that, and
    nothing enforced it. Measured 2026-08-25: `egeria-project.org` was fetched
    and embedded **three times in one batch**, once each for `egeria_git`,
    `egeria_python_git` and `egeria_workspaces_git`, 187 pages and 6018 chunks
    every time, ~175 seconds of the run.

    Keyed on the collection's own state rather than on a within-run memo,
    deliberately. `SurveyOrchestrator.run()` is per project, so there is no
    "run" spanning sibling repos to memoise against — and a state-keyed check
    also holds when the repos are surveyed days apart, or by the scheduler, or
    one at a time from the UI.

    **A previous run that stored nothing does not count.** `milvus` recorded a
    completed ingest with zero chunks after 400 failed fetches; treating that as
    "already done" would make a bad run permanent.

    **This repo counts as "anyone", and the first version excluded it — wrongly.**
    Skipping writes a zero-chunk record over whatever this repo held, so after
    two siblings skip, only the third still carries evidence the site is fresh;
    run last, it re-ingests. Observed immediately: `egeria_git` and
    `egeria_python_git` skipped in under a second and `egeria_workspaces_git`
    then spent 103 seconds re-fetching the site its own record said was current.
    The question is "has this collection been ingested recently", not "did
    somebody else do it".

    A deliberate re-ingest is therefore a separate concern from this check, and
    is not built: the step has no force-refresh path today, and adding one on
    the assumption that somebody wants it would be inventing a requirement.
    """
    from datetime import datetime, timedelta

    cutoff = datetime.utcnow() - timedelta(hours=SITE_FRESHNESS_HOURS)
    for other in registry.list_all():
        try:
            m = registry.query_metrics(other.slug, "website_ingestion") or {}
        except Exception:  # noqa: BLE001
            continue
        if not m or not (m.get("chunks") or 0):
            continue
        detail = m.get("detail") or {}
        if isinstance(detail, str):
            try:
                detail = json.loads(detail)
            except Exception:  # noqa: BLE001
                continue
        if detail.get("collection") != collection:
            continue
        when = str(m.get("surveyed_at") or "")
        try:
            if datetime.fromisoformat(when) < cutoff:
                continue
        except ValueError:
            continue
        return other.slug, when
    return None, None


def _extract_text(html: str) -> str:
    """Strip a page to its readable text.

    Deliberately not Docling here: these are ordinary HTML pages and Docling's
    converter added a heavyweight dependency on the hot path for no gain over
    tag-stripping — measured while building this, it extracted almost nothing
    from the two sites tried. Script/style/nav/header/footer go first so site
    chrome does not become chunks that match every query.
    """
    import html as _html
    import re

    body = re.sub(r"(?s)<(script|style|nav|header|footer|aside)[^>]*>.*?</\1>", " ", html)
    text = _html.unescape(re.sub(r"<[^>]+>", " ", body))
    return re.sub(r"\s+", " ", text).strip()


def _chunk(text: str, ctype) -> list[str]:
    """Split using the web_docs collection type's own chunk size, so website
    content is chunked the same way every other web content in this system is."""
    size = getattr(ctype, "chunk_size", 1000) or 1000
    overlap = getattr(ctype, "chunk_overlap", 100) or 0
    step = max(1, size - overlap)
    return [text[i:i + size] for i in range(0, len(text), step) if text[i:i + size].strip()]
